### ISSUE TITLE
Rethink AUTHORS file

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#17206]
Do we still need AUTHORS, not that things are more automaed on github?  Some of our first PRs are failing because the submitter is not in that file, and I don't think they should be expected to do it themselves, and I don't see any reason the committer need do it either now what there is all this automatic stuff already going on

**Comment by simcop2387** [comment]
As an outsider I'd say it probably shouldn't be the same check that it was, but it should probably be regenerated to include them somehow?  I know it's useful to see the new contributors between releases and other such things as that.

**Comment by atoomic** [comment]
Yeap we probably want to preserve the list of authors, my suggestion is that the test for authors should not be a blocker for someone submitting a PR, and thus only fail once smoke on blead on the official repo...

Which would be annoying as once merged the test will have to be fixed...
maybe we should consider a hook to automatically add missing authors on merge?
but probably too much trouble... I would say let's see how bad it is over time and how many new authors we have to add?

**Comment by karenetheridge** [comment]
I would simply add an item to the release manager's guide: "regenerate the AUTHORS file" -- so that it only needs to be updated at release time, rather than at every commit.  The test that checks the AUTHORS file would move to the section of porting tests that are only run to verify a release, rather than a normal test that is always run.

**Comment by atoomic** [comment]
I think this is a great idea @karenetheridge 
disable the unit test on general builds and enforce it when doing a release would be perfect

**Comment by khwilliamson** [comment]
A new issue came up.  What to do now that we are on github with with authors on github.  Especially ones whose email address is hidden.  Instead of an email we could somehow signal a github id.
@toddr @xsawyerx

**Comment by xsawyerx** [comment]
@khwilliamson I think using a GitHub ID instead of email when possible is a good idea. We'll need to readjust the test to handle that.

What I would be happy is if the test (or some preliminary script during release) can say "These are the entries that need to be added." If it has GitHub IDs, it can also check for names. It can also update the `AUTHORS` file itself when run manually.

**Comment by atoomic** [comment]
I've adjusted the existing script `Porting/checkAUTHORS.pl` to be update the AUTHORS file,
and altered the `Porting/release_managers_guide.pod` with that new step.

For new authors not already listed / known, we will try to use the GitHub account instead of the email address.

view PR #17404
