### ISSUE TITLE
Notify open tickets that their case has been moved to github.

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#17235]
@khw stated:

> If you opened a ticket, or commented on it, and we did not find your github id, you will now be completely left out of whatever happens to it, without any knowledge that you have been cut off.  I think that is unacceptable.  At the least, submitters and commenters on all open tickets should be sent an email about the transition.

**Comment by khwilliamson** [comment]
Tickets are getting closed or just commented on, and the OP is not getting notified.  Nor are other parties to the conversation who aren't on github.

This needs to be attended to quickly
@xsawyerx  @toddr

**Comment by xsawyerx** [comment]
Notifications were disabled when we made the transition to avoid flooding inboxes. This meant that, even when we have the GitHub ID of the person and mention them in the ticket, they still did not receive an initial notification that their ticket moved. @toddr, right?

The only option I can imagine is to update everyone on their (2 months and older) created tickets based on their email - at least for those we have an email. @toddr, what do you think?

This can only be an initial update. We can also group all notifications on one email, as in "Status of your older tickets."

Once we provide an update on the tickets, we cannot push additional updates for them on the tickets. They will need to register for them. This is because we cannot, using the GitHub API, have the ticket assigned to them. (This is doubly true for those users of whom we do not have a GH account ID.) We can include the instructions and a clear "for the old tickets you opened, you will need to follow these instructions and 'watch' the 'thread' to view updates" explanation.

@khwilliamson, what do you think?

**Comment by Grinnz** [comment]
This is not about GitHub notifications. This is about notifications to emails that opened tickets that do not have a GitHub ID, and so are getting nothing whatsoever now.

**Comment by Grinnz** [comment]
I think the best thing to do is, like you said, a one-time email to all emails that had opened or CC on RT tickets. Just one message per user, listing all of the tickets they are listed on that were migrated. Not sure if it's worth including those that were mapped to GH ids or not, depends how confident we are on that mapping.

**Comment by khwilliamson** [comment]
Grinnz's proposal  sounds reasonable

**Comment by toddr** [comment]
I believe @xsawyerx is going to be emailing all old RT openers shortly to indicate that their ticket has bee moved. I'll leave him to fill everyone in.

**Comment by karenetheridge** [comment]
> I believe @xsawyerx is going to be emailing all old RT openers shortly to indicate that their ticket has bee moved. I'll leave him to fill everyone in.

This sounds good.  Useful information to include for each item:

- RT # of ticket
- subject of ticket
- date opened
- link to migrated github issue
- current status of github issue (open/closed etc), and possibly all labels on the issue? (e.g. it is useful to tell a submitter that their ticket "needs more information")

**Comment by jkeenan** [comment]
Given the email sent out last week by @toddr , what remains before we can close this ticket?

Thank you very much.
Jim Keenan

**Comment by toddr** [comment]
yep.
