### ISSUE TITLE
[infra] Automate windows testing by enabling Appveyor for Perl push and pull requests

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#17286]
This is a TODO being added to https://github.com/Perl/perl5/projects/1 to get Appveyor working for Perl development

**Comment by Corion** [comment]
A rough (rough!) prototype lives at

https://github.com/Corion/perl5/blob/corion/appveyor/.appveyor.yml

but I'm still working on that. See for example

https://ci.appveyor.com/project/Corion/perl5/builds/28753498/job/72b35u5p6g4xfx7w

(not finished yet)

**Comment by Corion** [comment]
I've ditched AppVeyor because the filesystem seems to be weird there under Cygwin.

There is a pull request to implement this as Github Actions:

https://github.com/Perl/perl5/pull/17299

I may revisit AppVeyor with the things learned from Github Actions later, but Github Actions should allow us more flexibility.

**Comment by toddr** [comment]
Fixed in #17299
