### ISSUE TITLE
corruption in repo

### ISSUE THREAD

**Issue by noahfriedman** [Perl/perl5#17321]
The repository appears to be corrupt.  If I try to clone with `transfer.fsckObjects=true`, I get the following error:

> $ git -c 'transfer.fsckObjects=true' clone https://github.com/perl/perl5.git
> Cloning into 'perl5'...
> remote: Enumerating objects: 392, done.
> remote: Counting objects: 100% (392/392), done.
> remote: Compressing objects: 100% (274/274), done.
> error: object d958e86c431726ba4d228224bff4ae5994727ded: missingSpaceBeforeDate: invalid author/committer line - missing space before date
> fatal: fsck error in packed object
> fatal: index-pack failed
> $

A download without checking objects followed by `git fsck` shows the following errors:

> error in commit d958e86c431726ba4d228224bff4ae5994727ded: missingSpaceBeforeDate: invalid author/committer line - missing space before date
> error in commit 13b79730adea97e660de84bbe67f9d7cbe344302: missingSpaceBeforeDate: invalid author/committer line - missing space before date

**Comment by jkeenan** [comment]
> git -c 'transfer.fsckObjects=true' clone https://github.com/perl/perl5.git

Confirmed.
```
$ git -c 'transfer.fsckObjects=true' clone https://github.com/perl/perl5.git
Cloning into 'perl5'...
remote: Enumerating objects: 552, done.
remote: Counting objects: 100% (552/552), done.
remote: Compressing objects: 100% (201/201), done.
error: object d958e86c431726ba4d228224bff4ae5994727ded: missingSpaceBeforeDate: invalid author/committer line - missing space before date
fatal: fsck error in packed object
fatal: index-pack failed
```
Does anyone know how to repair the repository?

More particularly, is it possible to repair a problem in a commit from nearly 22 years ago (and in a former VCS)?
```
commit d958e86c431726ba4d228224bff4ae5994727ded
Author:     Murray Nesbitt <mjn@pathcom.com>
AuthorDate: Tue Mar 3 19:13:17 1998 +0000
Commit:     Tim Bunce <TimBunce@ig.ac.uk>
CommitDate: Tue Mar 3 19:13:17 1998 +0000

    "Fix infinite loop on unlink() failure in File::Path::rmtree()",
```
Thank you very much.
Jim Keenan

**Comment by xenu** [comment]
It seems that a repair was attempted, probably during the migration to github, but the fix isn't complete.

Commit d958e86c431726ba4d228224bff4ae5994727ded was replaced with 7d30fe4839ae753ca83085806b7e44c13cd4b85e, while 13b79730adea97e660de84bbe67f9d7cbe344302 was replaced with 6c8d1f3289749a7c1d9bb01066b9b40949d4a48e. Both commits weren't committed to blead, they only exist in maint-5.004 branch

There are two problems left:

1. 7d30fe4839ae753ca83085806b7e44c13cd4b85e has a weird "Author" value, it probably should be replaced with `Murray Nesbitt <mjn@pathcom.com>`:
```
commit 7d30fe4839ae753ca83085806b7e44c13cd4b85e
Author:     author Murray Nesbitt mjn@pathcom.com, Tim Bunce Tim.Bunce@ig.co.uk 888952397 +0000 <author Murray Nesbitt mjn@pathcom.com, Tim Bunce Tim.Bunce@ig.co.uk 888952397 +0000>
AuthorDate: Tue Mar 3 19:13:17 1998 +0000
Commit:     Tim Bunce <TimBunce@ig.ac.uk>
CommitDate: Tue Mar 3 19:13:17 1998 +0000
```

2. While the commit d958e86c431726ba4d228224bff4ae5994727ded was removed from maint-5.004 branch, it still exists in a tag, which is the reason why `git gc` didn't remove it and `git fsck` still complains:

```
> git branch -a --contains d958e86c431726ba4d228224bff4ae5994727ded
> git tag --contains d958e86c431726ba4d228224bff4ae5994727ded
perl-5.004_05
```

**Comment by Grinnz** [comment]
This is a known historical issue. The repair attempt was mentioned in https://www.nntp.perl.org/group/perl.perl5.porters/2019/10/msg256484.html. I recall that there was a guide somewhere showing how to correct this locally for bisecting and such but can't find it.

**Comment by demerphq** [comment]
FWIW, the way to see this problem is:

git cat-file -p d958e86c431726ba4d228224bff4ae5994727ded
tree 126caac06dc9acbc02ca92f4205e1337ae62c8e9
parent ef113ac011057424344909ecfe7fe97330cbfc46
author Murray Nesbitt <mjn@pathcom.com>, Tim Bunce <Tim.Bunce@ig.co.uk> 888952397 +0000
committer Tim Bunce <TimBunce@ig.ac.uk> 888952397 +0000

"Fix infinite loop on unlink() failure in File::Path::rmtree()",
         #F076
Msg-ID:  <199802061100.LAA16423@toad.ig.co.uk>
 Files:  lib/File/Path.pm

p4raw-id: //depot/maint-5.004/perl@707

**Comment by toddr** [comment]
I did in fact try to fix this during the migration. I will look again at this today.

**Comment by toddr** [comment]
FTR: Throw this in your .gitconfig prior to clone fixes the issue.

```
 [transfer]
 fsckObjects = false
```

**Comment by khwilliamson** [comment]
What should be done with this ticket? @toddr et. al.

**Comment by toddr** [comment]
I tried with limited success to fix the commit attached to the tag. This seemed minimally invasive. It required re-writing some history to pull it off because a rebase was involved if I remember correctly. If we have a problem with a commit attached to a branch, I'm not sure what to suggest here. I am loathed to re-write history on that.

At one point I was going to ask @bk2204 for his advice on this as he is a contributor to git and has also contributed to this project in the past.

@bk2204: is there any advice you can give us? 🥺

**Comment by bk2204** [comment]
It's known that some histories contain various corrupt commits.  In general, GitHub requires all commits to pass `git fsck`, but for large projects with extensive histories like Perl, usually they'll make an exception to avoid having to rewrite the history of the project.  This is one of those cases.

My general advice here is just to run `git -c transfer.fsckObjects=false clone https://github.com/perl/perl5.git` and call it a day.  Mistakes happen and in this case, they're prevented from happening again, so I personally wouldn't consider it a big deal.

You _can_ use `git rebase` to fix this, but that is going to set you to the committer for all of the commits.  It is probably easier to use `git filter-branch` or `git filter-repo` (the latter, I believe, is more preferred these days, but is an external tool) to rewrite the author of that commit.  I will mention of course that this rewrites history and the object IDs of that commit and the succeeding ones in any branch it's on.  I can't really give advice on how to use those tools effectively since I haven't, but you could ask on the Git user mailing list mentioned at https://git-scm.com/community and I'm sure someone most knowledgeable would be delighted to help.

Finally, a personal point of note: while I have contributed to various modules, I am not, to my knowledge, one of the illustrious contributors to this repo.

**Comment by demerphq** [comment]
On Sun, 17 Apr 2022 at 23:20, brian m. carlson ***@***.***>
wrote:

> Finally, a personal point of note: while I have contributed to various
> modules, I am not, to my knowledge, one of the illustrious contributors to
> this repo.
>
I guess there is a confusion with a different Brian Carlson who wrote this
commit:

commit 1735f6f53ca19f99c6e9e39496c486af323ba6a8
Author: Brian Carlson ***@***.***>
Date:   Wed Nov 28 08:54:33 2012 -0500

    Fix misparsing of maketext strings.

    Case 61251: This commit fixes a misparse of maketext strings that could
    lead to arbitrary code execution.  Basically, maketext was compiling
    bracket notation into functions, but neglected to escape backslashes
    inside the content or die on fully-qualified method names when
    generating the code.  This change escapes all such backslashes and dies
    when a method name with a colon or apostrophe is specified.

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by haarg** [comment]
I think that rewriting the history of the `maint-5.004` branch and `perl-5.004_05` tag to correct these commits would be reasonable. It's very unlikely anyone would be basing any work on those, and they aren't gpg signed or anything.

I've prepared fixed versions of these at https://github.com/haarg/perl-cleanup. It changes the `maint-5.004` branch, the `perl-5.004_05`, `timinator`, and `timinatorII` tags, to fix the broken commits. It also re-points `perl-5.004_05` to properly be on the `maint-5.004` branch history. The previous attempts at repairing these commits had apparently rebased the branch, so it was an alternate history where half the commits had their committer attributed to @toddr.

**Comment by bk2204** [comment]
> I guess there is a confusion with a different Brian Carlson who wrote this commit: commit [1735f6f](https://github.com/Perl/perl5/commit/1735f6f53ca19f99c6e9e39496c486af323ba6a8) 

Nope, that was me.  That was some time ago and I'd forgotten I'd sent it in.

**Comment by toddr** [comment]
> I've prepared fixed versions of these at https://github.com/haarg/perl-cleanup. It changes the `maint-5.004` branch, the `perl-5.004_05`, `timinator`, and `timinatorII` tags, to fix the broken commits. It also re-points `perl-5.004_05` to properly be on the `maint-5.004` branch history. 

Excellent! Thanks for looking at this. I don't think anyone would object to a force push on 5.004 branches or tags. My vote is to force push away.

**Comment by haarg** [comment]
I believe that the maint-5.004 branch is protected, so I don't think I'd be able to replace it. It's probably best if a repository admin does the force push.

**Comment by haarg** [comment]
@toddr, could you push the fixed maint-5.004 branch? It should be as simple as:
```
$ git fetch https://github.com/haarg/perl-cleanup.git maint-5.004:maint-5.004
$ git push origin -f maint-5.004
```
I believe you have permission to do the force push, but if not, you have administrator permissions on the repository and can change the permissions.

**Comment by toddr** [comment]
I can take a look at an hour

**Comment by toddr** [comment]
Force pushed. Testing shows:
```
$>git -c 'transfer.fsckObjects=true' clone https://github.com/perl/perl5.git
Cloning into 'perl5'...
remote: Enumerating objects: 606627, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 606627 (delta 8), reused 18 (delta 8), pack-reused 606608
Receiving objects: 100% (606627/606627), 317.30 MiB | 23.23 MiB/s, done.
Resolving deltas: 100% (440789/440789), done.
```

**Comment by toddr** [comment]
If someone wants to clean this bug up as far as git fsck goes, you may have to update or remove some remotes. For instance, I had to remove my old booking remote because it, of course, hasn't been cleaned up.

I did something along the lines of: `git branch -a --contains d958e86c431726ba4d228224bff4ae5994727ded`

You'll also need to force fetch some tags from p5p: `git fetch --tags -f p5p`

Additionally, you may have to clean things up locally:
```
git reflog expire --expire=now --all; git gc --prune=now
```

At which point fsck should come back clean:
```
$>git fsck
Checking object directories: 100% (256/256), done.
Checking objects: 100% (728702/728702), done.
Checking connectivity: 728702, done.
Verifying commits in commit graph: 100% (140137/140137), done.
```
