### ISSUE TITLE
NetBSD 8.1 and "don't know how to make w"

### ISSUE THREAD

**Issue by noloader** [Perl/perl5#17543]
**Description**
I'm building Perl 5.30.1 from the release tarball on NetBSD 8.1. After Configure and during `make`:

```
$ gmake
...
gmake[1]: Leaving directory '/home/jwalton/perl-5.30.1/cpan/Digest-SHA'
./miniperl -Ilib make_ext.pl lib/auto/Encode/Encode.so  MAKE="gmake" LIBPERL_A=libperl.a LINKTYPE=dynamic
Generating a Unix-style Makefile
Writing Makefile for Encode
gmake[1]: Entering directory '/home/jwalton/perl-5.30.1/cpan/Encode'
make[2]: make[2]: don't know how to make w. Stop

make[2]: stopped in /home/jwalton/perl-5.30.1/cpan/Encode/Byte
gmake[1]: *** [Makefile:587: subdirs] Error 2
gmake[1]: Leaving directory '/home/jwalton/perl-5.30.1/cpan/Encode'
gmake[1]: Entering directory '/home/jwalton/perl-5.30.1/cpan/Encode'
make[2]: make[2]: don't know how to make w. Stop
```

I see two similar reports at [Not OK: perl v5.8.8 on i386-freebsd 4.9-release-p8 ](https://github.com/Perl/perl5/issues/8311) and [Not OK: perl v5.8.4 on i386-freebsd 4.6.2-release-p12](https://github.com/Perl/perl5/issues/7296), but I don't see the resolution.

I also found [Trouble compiling modperl with FreeBSD11](https://www.mail-archive.com/modperl@perl.apache.org/msg28678.html), but I am already using GNU make.

**Steps to Reproduce**
```
./Configure -des ...
gmake
```

I am supplying `-Dextras="Text::Template Test::More`, if it matters. Otherwise I have a normal assortment of `CPPFLAGS`, `CFLAGS` and `LDFLAGS`.

**Some analysis**

```
gmake[1]: Entering directory '/home/jwalton/perl-5.30.1/cpan/Encode'
make[2]: make[2]: don't know how to make w. Stop
```

It looks like Perl uses Gmake, but the the CPAN file switches to Make. I see the Perl scripts setting `MAKE="gmake"`. I don't know how to fix that.

**Expected behavior**
A clean build.

**Perl configuration**
No `perl -V` yet. I am still trying to build the package. Ugh...

**Comment by richardleach** [comment]
Please could you attach the contents of the _cpan/Encode/Makefile_ that gets generated?

Possibly something to do with whitepace in the generated file: https://stackoverflow.com/questions/10216480/error-dont-know-how-to-make

**Comment by doughera88** [comment]
The simplest workaround is to use a plain 'make' instead of 'gmake'.  

More details:  Configure defaults to using the default system 'make'
command, so your config.sh contains a line   make='make' .  This gets
passed along to other parts of the build system that build and use
Makefiles.  If you really want to use gmake, you could run 
Configure -Dmake=gmake.

The problem arises when the built Makefile in cpan/Encode tries
to recursively build Encode's subdirectories.  The recursive make
automatically gets the '-w' option added to print the directory.
That flag also gets added to the 'MAKEFLAGS' environment variable.
Unfortunately, gmake and make use and interpret that flag in incompatible ways.

In gmake, you get MAKEFLAGS='w'.  If you were to invoke Berkeley make with -w,
however, it would include the dash and you would have MAKEFLAGS=-w.  The result
of the mixed calls here is that gmake sets MAKEFLAGS=w, but then that gets
handed to Berkeley make, which interprets the w (without a hyphen) as a
makefile target, and issues the error message "don't know how to make w".

The glue file make_ext.pl is intended to handle this case (see the
comments around line 124), but clearly isn't always.  I haven't looked at this carefully, 
or tested it at all, but the following patch might work:

```
diff --git a/make_ext.pl b/make_ext.pl
index 0280a027cf0..1371ff14d97 100644
--- a/make_ext.pl
+++ b/make_ext.pl
@@ -519,7 +519,7 @@ EOM
 	    my $libd = VMS::Filespec::vmspath($lib_dir);
 	    push @args, "INST_LIB=$libd", "INST_ARCHLIB=$libd";
 	} else {
-	    push @args, 'INSTALLDIRS=perl', 'INSTALLMAN1DIR=none',
+	    push @args, "MAKE=@make", 'INSTALLDIRS=perl', 'INSTALLMAN1DIR=none',
 		'INSTALLMAN3DIR=none';
 	}
 	push @args, @$pass_through;

```

Again, though, the simplest workaround is to use a plain 'make' instead of
'gmake'.

**Comment by jkeenan** [comment]
I believe that since we have provided the original poster with advice and a workaround for his problem, this issue can be closed.

Any objection?

**Comment by doughera88** [comment]
On Wed, Apr 08, 2020 at 12:19:06PM -0700, James E Keenan wrote:
> I believe that since we have provided the original poster with advice and a workaround for his problem, this issue can be closed.
> 
> Any objection?

No objections.  (I supplied a possible patch, but it's not well-tested
low priority, so I don't mind if it falls through the cracks.)
Close it.

Thanks for looking after the queue.

-- 
    Andy Dougherty		doughera@lafayette.edu
