### ISSUE TITLE
[doc] perldiag and perldeprecation should be cleaned up in regards to 5.32

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#17757]
**Where**

perldiag perldeprecation
**Description**

These modules have out-dated text about 5.32, referring to it in the future.  But the future is upon us.

**Comment by khwilliamson** [comment]
s/modules/documents/

**Comment by jkeenan** [comment]
> **Where**
> 
> perldiag perldeprecation
> **Description**
> 
> These modules have out-dated text about 5.32, referring to it in the future. But the future is upon us.

@khwilliamson, https://github.com/Perl/perl5/pull/17758 handles **some** of these instances.  However, I don't well enough understand what was **actually** done with respect to the following doc sections to be able to revise:

**pod/perldeprecation.pod**
```
=head3 Unescaped left braces in regular expressions
...
C<{> got a deprecation warning.  Some cases started warning in Perl 5.26,
and were made fatal in Perl 5.30.  Other cases started in Perl 5.28,
and will be made fatal in 5.32.
```
**pod/perldiag.pod**
```
=item Unescaped left brace in regex is passed through in regex; marked by S<<-- HERE> in m/%s/
...
The cases which are still allowed will be fatal in Perl 5.32.
...
=item Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by S<<-- HERE> in m/%s/

```
I know that the second diagnostic above was eliminated -- but my hunch is that some of the text that follows is still valid.  My impression is that there were certain cases we did not fatalize because they would cause too much breakage in CPAN and elsewhere.  Please review.

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
Here's some dangling ones
=item File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead.
 =item Deprecated use of my() in false conditional. This will be a fatal error in Perl 5.30

**Comment by xsawyerx** [comment]
I provided a PR in #17801.
