### ISSUE TITLE
Reduce the ambiguity of warnings triggered by resolving undef via a non-existent hash key within grep and map

### ISSUE THREAD

**Issue by ghost** [Perl/perl5#17818]
When writing Perl, I almost always fatalize warnings in the "uninitialized" category. Consider the following:

```
$ perl -Mwarnings -e 'sub f { my %p = @_; "$p{wrong_key}"; }; f()'
Use of uninitialized value $p{"wrong_key"} in string at -e line 1.
```

This is a good warning. Now, consider the following:

```
$ perl -Mwarnings -e 'sub f { my %p = @_; map { "$p{$_}" } qw/wrong_key/; }; f()'
Use of uninitialized value within %p in string at -e line 1.
```

This is a poor warning because it does not reveal the value of the key that was used to resolve the undefined value.

Note that this ambiguity only arises where the key does not exist.

```
$ perl -Mwarnings -e 'sub f { my %p = @_; map { "$p{$_}" } qw/key_for_undef/; }; f(key_for_undef => undef)'
Use of uninitialized value $p{"key_for_undef"} in string at -e line 1.
```

My wish is that the offending key is reported in all cases.

**Comment by xsawyerx** [comment]
This makes sense to me.

**Comment by tonycoz** [comment]
It isn't possible to fix this for the general case, ie. `$foo{complex expression}` since by the time this warning is reported the results of the complex expression have been discarded, and it isn't practical to re-evaluate the expression, it may have side-effects, it may work with variables with magic.

For values that do exist in the hash or array the report_uninit() implementation takes the undefined SV and searches the hash or array (if it's relatively small) to find the index.

For elements that do not exist this obviously fails.

My PR tries to handle the simple cases that OP_MULTIDEREF picks up by handling simple SV indexes just as the code handles constants, but again, this isn't a general solution, and I don't think trying to handle more complex cases is worth the time.
