### ISSUE TITLE
Don't only say Unescaped brace in regex

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#17812]
```
$ perl -nwe '/.{,4}/ && s/a/b/;' /dev/null
Unescaped left brace in regex is illegal here in regex;
marked by <-- HERE in m/.{ <-- HERE ,4}/ at -e line 1.
$ perl -nwe '/.{2,4}/ && s/a/b/;' /dev/null
$
```
It should also say
```
or, you forgot to fill in two values in {x,y}
```
which is indeed much more likely here.

v5.30.2.

**Comment by jkeenan** [comment]
> ```
> $ perl -nwe '/.{,4}/ && s/a/b/;' /dev/null
> Unescaped left brace in regex is illegal here in regex;
> marked by <-- HERE in m/.{ <-- HERE ,4}/ at -e line 1.
> $ perl -nwe '/.{2,4}/ && s/a/b/;' /dev/null
> $
> ```
> 
> It should also say
> 
> ```
> or, you forgot to fill in two values in {x,y}
> ```
> 
> which is indeed much more likely here.
> 
> v5.30.2.

Perhaps the problem is the other way around.  In recent years, we've first warned, then fatalized, many cases of `Unescaped left brace in regex`.  Perhaps the real problem is that we have not yet fatalized the unescaped left brace inside the second regex example provided:
```
$ perl -nwe '/.{2,4}/ && s/a/b/;' /dev/null
```
Why doesn't the dog bark here (yet)?

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
The second example is a legitimate use of a brace as syntax, escaping it would break the expression.

**Comment by khwilliamson** [comment]
On 5/29/20 6:42 AM, 積丹尼 Dan Jacobson wrote:
> |$ perl -nwe '/.{,4}/ && s/a/b/;' /dev/null Unescaped left brace in 
> regex is illegal here in regex; marked by <-- HERE in m/.{ <-- HERE ,4}/ 
> at -e line 1. $ perl -nwe '/.{2,4}/ && s/a/b/;' /dev/null $ |
> 
> It should also say
> 
> |or, you forgot to fill in two values in {x,y} |
> 
> which is indeed much more likely here.
> 
> v5.30.2.
> 

The syntax is now illegal, but will become legal in 5.33, where 0 is 
substituted by the parser for the missing lower bound, bringing Perl 
into conformance with the behavior of other languages.

**Comment by jidanni** [comment]
Maybe v5.30's warning should then be changed to say that "syntax coming soon, not legal just yet"...
Or maybe no more changes are being accepted for v5.30, v5.31, v5.32.

**Comment by demerphq** [comment]
On Wed, 3 Jun 2020 at 00:07, Karl Williamson <notifications@github.com>
wrote:

> On 5/29/20 6:42 AM, 積丹尼 Dan Jacobson wrote:
> > |$ perl -nwe '/.{,4}/ && s/a/b/;' /dev/null Unescaped left brace in
> > regex is illegal here in regex; marked by <-- HERE in m/.{ <-- HERE ,4}/
> > at -e line 1. $ perl -nwe '/.{2,4}/ && s/a/b/;' /dev/null $ |
> >
> > It should also say
> >
> > |or, you forgot to fill in two values in {x,y} |
> >
> > which is indeed much more likely here.
> >
> > v5.30.2.
> >
>
> The syntax is now illegal, but will become legal in 5.33, where 0 is
> substituted by the parser for the missing lower bound, bringing Perl
> into conformance with the behavior of other languages


Weird, I could have sworn that older perls supported {,N}. I need to check
that someday.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by xsawyerx** [comment]
> Maybe v5.30's warning should then be changed to say that "syntax coming soon, not legal just yet"...
> Or maybe no more changes are being accepted for v5.30, v5.31, v5.32.

Considering this will be amended as Karl described in 5.33.x, and that 5.32.0 is now hitting RC2 (full freeze mode with only major exceptions approved), I don't see how we could produce this warning. There just isn't enough "meantime" for it. Sorry.

Generally speaking, I'm cautious of "meantime warnings." They're good for deprecations because deprecations are time-based anyway, but for "usage warnings," I would expect a warning to last a while. A temporary warning for a single release might be too much. (Not entirely against it, just cautious.)
