### ISSUE TITLE
perl-5.32.0 perldelta

### ISSUE THREAD

**Issue by wwlwpd** [Perl/perl5#17947]
**Where**
https://metacpan.org/changes/release/XSAWYERX/perl-5.32.0#perlxs

**Description**
It's misleading to say, "Suggest using libffi for simple library bindings." The link is also broken, so this likely causes the interested party in searching cpan for "libffi".

This leads to https://metacpan.org/pod/FFI, where the author says, "NOTE: Newer and better maintained `FFI` modules such as `FFI::Platypus` provide more functionality and so it is strongly recommend that you use one of them for new projects and even consider migrating to one of them for existing projects."

When in fact, the `perlxs` (https://perldoc.perl.org/perlxs.html#Introduction) actually says, "For simple bindings to C libraries as well as other machine code libraries, consider instead using the much simpler libffi interface via CPAN modules like `FFI::Platypus` or `FFI::Raw`."

It is not lost on me that `FFI`'s author is also the author of `FFI::Platypus`.

**Comment by Grinnz** [comment]
FWIW the link is not broken, as you can see at https://perldoc.pl/perl5320delta#perlxs it intends to go to the correct page, metacpan is not always capable of rendering all of the core perldocs properly because it does not work off an installed instance of Perl.
(The source for what ends up getting installed as perlxs is visible on metacpan at https://metacpan.org/pod/release/XSAWYERX/perl-5.32.0/dist/ExtUtils-ParseXS/lib/perlxs.pod)

Perhaps the perldelta could be more specific, but `libffi` is the library that both FFI::Platypus and FFI::Raw make use of to provide the functionality.

**Comment by jkeenan** [comment]
> FWIW the link is not broken, as you can see at https://perldoc.pl/perl5320delta#perlxs it intends to go to the correct page, metacpan is not always capable of rendering all of the core perldocs properly because it does not work off an installed instance of Perl.
> (The source for what ends up getting installed as perlxs is visible on metacpan at https://metacpan.org/pod/release/XSAWYERX/perl-5.32.0/dist/ExtUtils-ParseXS/lib/perlxs.pod)
> 
> Perhaps the perldelta could be more specific, but `libffi` is the library that both FFI::Platypus and FFI::Raw make use of to provide the functionality.

Is this ticket closable?

**Comment by Grinnz** [comment]
I'm not sure what action could be taken here. My only suggestion would be to add to that perldelta line: "Suggest using libffi *via FFI::Platypus or FFI::Raw* for simple library bindings."

**Comment by xsawyerx** [comment]
Fixed with 45233210007b2012e0dd03228d3aa475dd6b48b1 using language pretty much lifted from `perlxs`.
