### ISSUE TITLE
[doc][feature] Regexp quantifiers: match at most n times

### ISSUE THREAD

**Issue by epa** [Perl/perl5#18264]
Perl's regexp language supports numbered quantifiers, as documented in perldoc:

           {n}         Match exactly n times
           {n,}        Match at least n times
           {n,m}       Match at least n but not more than m times

GNU grep supports an additional syntax:

           {,m}        The preceding item is matched at most m times.  This is a GNU extension.

So for example `grep -E 'ab{,2}c'` matches `ac`, `abc`, and `abbc`, but not `abbbc`.  Of course, it is syntactic sugar for `ab{0,2}c`.

In perl 5.30 this construct gives an error about unescaped left brace, so I think there is scope for giving it a meaning without breaking existing code -- if you can disregard code originally written in the days before the left brace needed escaping, which hasn't been updated for the deprecation that was originally added in 5.16, and which will fail to compile on recent perl versions.

If you don't want to support the at-most-n syntax `{,n}`, then I suggest an explicit note in the documentation that it's not allowed.  Otherwise it seems a logical thing to use given that `{n,}` works and the fact that `grep -E` supports it on many systems.  Possibly, too, you could have an explicit diagnostic, but if you go to the trouble of adding that, it wouldn't be much more effort to implement the feature.

**Comment by khwilliamson** [comment]
On 10/21/20 2:44 AM, Ed Avis wrote:
> Perl's regexp language supports numbered quantifiers, as documented in 
> perldoc:
> 
> |{n} Match exactly n times {n,} Match at least n times {n,m} Match at 
> least n but not more than m times |
> 
> GNU grep supports an additional syntax:
> 
> |{,m} The preceding item is matched at most m times. This is a GNU 
> extension. |
> 
> So for example |grep -E 'ab{,2}c'| matches |ac|, |abc|, and |abbc|, but 
> not |abbbc|. Of course, it is syntactic sugar for |ab{0,2}c|.
> 
> In perl 5.30 this construct gives an error about unescaped left brace, 
> so I think there is scope for giving it a meaning without breaking 
> existing code -- if you can disregard code originally written in the 
> days before the left brace needed escaping, which hasn't been updated 
> for the deprecation that was originally added in 5.16, and which will 
> fail to compile on recent perl versions.
> 
> If you don't want to support the at-most-n syntax |{,n}|, then I suggest 
> an explicit note in the documentation that it's not allowed. Otherwise 
> it seems a logical thing to use given that |{n,}| works and the fact 
> that |grep -E| supports it on many systems. Possibly, too, you could 
> have an explicit diagnostic, but if you go to the trouble of adding 
> that, it wouldn't be much more effort to implement the feature.
> 

I have planned to add this feature for quite a long time, and I have had 
most of the code already written to do so, but there were various 
impediments, removed one release at a time.  Now the one remaining issue 
is what to do about white space within braces, which is being discussed 
on another thread.  Unless there is further discussion there, that will 
be resolved so that horizontal white space between tokens will be 
allowed within all brace constructs at all times.

It doesn't look like there was ever a ticket for this; I thought there 
was.  There was certainly agreement on this list about doing this quite 
a few years ago.  So we can use this ticket for this feature.  Thank you.

**Comment by khwilliamson** [comment]
This is now fully implemented
