### ISSUE TITLE
Perl's internal printf "%#p" format does not prefix with "0x..."

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#18289]
Platform's printf() prefixes "0x..." on integers and pointers with the `#` flag:

```c
printf("%#x", 15);  // 0xf
printf("%#p", (void *)15); // 0xf
```

Perl's `warn()` uses its own internal implementation which does not do this for `%#p`.

It would be useful if it did.

**Comment by hvds** [comment]
That sounds entirely reasonable to me; it's hard to tell why we don't, since the "unknown" check below was added as part of an apparently unrelated megapatch back in the Perforce days.

We repurpose `%p` for a variety of additional constructs, some of which are strings; but a `%#s` format will happily silently ignore the `#`, so we don't need to take avoiding action on that account.

I'm having difficulty doing a test run right now, but I think the change below would cause only the explicit `"%#p" is INVALID` test to complain.

```
index 57fd65a5b8..d21e9ac0c4 100644
--- a/sv.c
+++ b/sv.c
@@ -12417,9 +12417,6 @@ Perl_sv_vcatpvfn_flags(pTHX_ SV *const sv, const char *const pat, const STRLEN p
            /* INTEGERS */
 
        case 'p':
-           if (alt)
-               goto unknown;
-
             /* %p extensions:
              *
              * "%...p" is normally treated like "%...x", except that the
@@ -12493,6 +12490,7 @@ Perl_sv_vcatpvfn_flags(pTHX_ SV *const sv, const char *const pat, const STRLEN p
 
            uv = PTR2UV(args ? va_arg(*args, void*) : argsv);
            base = 16;
+            c = 'x';    /* in case of '#' in the format */
            goto do_integer;
 
        case 'c':
```

**Comment by dmah42** [comment]
I have this change made locally and I can confirm that the `"%#p" is INVALID` test is the only one that is broken. If I add the equivalent test that we use for `"%p"` to also test `"%#p"` (The "Course hack") would that be sufficient for a patch to fix this?

**Comment by hvds** [comment]
@dominichamon I think it would be sufficient, yes.
