### ISSUE TITLE
[feature] Warning for repeated 'use'

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18362]
Perhaps e.g.,
```
use warnings;
use Data::Dumper;
use XML::LibXML;
use Data::Dumper;
```
should warn "You already said 'use Data::Dumper;'".

Nice to know, before sending one's code to some competition or something. I don't think perltidy etc. should be responsible for warning.

So I guess there would need to be a counter / detector, if the exact same use statement is used.

Yes, one could also do
`$ sort file.pl | uniq --repeated`

**Comment by Grinnz** [comment]
Repeated requires are intentionally no-ops so that different files don't need to know whether someone else loaded the module yet. Repeated uses will import from the module each time which can have arbitrary functionality, so it is impossible for Perl to know whether it is an abnormal usage of the module.
