### ISSUE TITLE
pack/unpack format 'D' unknown when perl built with -Dusequadmath

### ISSUE THREAD

**Issue by Tux** [Perl/perl5#18512]
```
$ perl5.32.0 -v | grep 5.32
This is perl 5, version 32, subversion 0 (v5.32.0) built for x86_64-linux-thread-multi-ld
$ perl5.32.0 -V:.*do?u?ble?size
doublesize='8';
longdblsize='16';
$ perl5.32.0 -wE'say length pack "D" => 1.25'
16
```
```
$ perl5.32.1 -v | grep 5.32
This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi-quadmath
$ perl5.32.1 -V:.*do?u?ble?size
doublesize='8';
longdblsize='16';
$ perl5.32.1 -wE'say length pack "D" => 1.25'
Invalid type 'D' in pack at -e line 1.
```
Which is easy to explain from the code in pp_pack.c
```
#if defined(HAS_LONG_DOUBLE) && defined(USE_LONG_DOUBLE)
        case 'D':
```
with no alternative code for `'D'`. Note that `-Duselongdouble` and `-Dusequadmath` are mutually exclusive

**Comment by Leont** [comment]
I don't see any reason for this to depend on `defined(USE_LONG_DOUBLE)`. Seems to me like getting rid of those should eliminate this issue.

**Comment by sisyphus** [comment]
IIUC @Leont's suggestion wouldn't DWIM for me when nvtype is double.
I was actually thinking that the solution would be to
```
replace
defined(USE_LONG_DOUBLE)
with
(defined(USE_LONG_DOUBLE) || defined(USE_QUADMATH))
```
On a perl whose nvtype is double, <code>pack "D", $x</code> would simply take the double $x, and fill the extra bits with zeros.
So, on a perl whose nvtype is (80-bit) long double, <code>unpack "h*", pack "D>", 2.4</code> will produce:
000000000000040099999999999999a9
Whereas on a perl whose nvtype is double, the same code would (if <code>pack "D>",..</code> were allowed) produce:
00000000000004009999999999998900

That doesn't DWIM for me.
However, on a quadmath build, <code>pack "D",..</code> will produce the correct output, save for the rare occurrence when the double rounding of the input value throws the result out by one ULP.
I think it is expected that the "D" formatting be allowed on USE_QUADMATH builds. (In fact, I was surprised to see that it currently isn't.)

**Comment by Leont** [comment]
> IIUC @Leont's suggestion wouldn't DWIM for me when nvtype is double.

`HAS_LONG_DOUBLE` tells us we can do `long double`, `USE_LONG_DOUBLE` tells us `NV` is `long double`. The size of NV should not matter for this purpose. If the compiler supports `long double` it should all work, right?

What I'm really saying is that this should work regardless of both `uselongdouble` and `usequadmath`, it should only depend on compiler support.

**Comment by sisyphus** [comment]
Could it be arranged so that <code> pack "D", $str</code> will evaluate $str using strtold() when nvtype is double ?
In such a case, on both "double' and '-Duselongdouble' builds, I envisage that the return will then be identical.
I can see usefulness in that - and I could easily train my thought process to believe that it's providing both what I expect and what I want.

Of course, it goes against the usual expectation that strings be numified in accordance with the underlying nvtype.
But the excuse for that change in behaviour could easily be "That's what happens when you specify "D" formatting - it's exactly what you've asked for".

However, I don't see much value in being able to obtain the "D" formatting of a double that has been cast to a long double.
I can see it causing some confusion, too .... but maybe that's just bad vision on my part. (Though I *am* wearing new prescription specs that I picked up only yesterday.)
