### ISSUE TITLE
quadmath_format_valid rejects "%+.17g"

### ISSUE THREAD

**Issue by mohawk2** [Perl/perl5#18651]
**Description**
PDL's recently-added use of `%+.17g` (see https://github.com/PDLPorters/pdl/blob/dc5a0284c8d70dc03bf63506edb4c6b8b9b63977/Basic/Core/pdl.h.PL#L55) is rejected as invalid on Perl 5.33.7 with quadmath. This is especially regrettable since PDL doesn't yet fully support quadmath and long doubles, it's on the roadmap to do so, and this is a bit of a blocker.

**Steps to Reproduce**
Build and test PDL 2.029 on Perl 5.33.7 with quadmath on at least Cygwin - see http://www.cpantesters.org/cpan/report/23fa1dc3-6f60-1014-9102-2ba2af1defc7

**Expected behavior**
Since https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libquadmath/quadmath_005fsnprintf.html has example code with `%+`, it seems the Perl function should not reject it out of hand.

**Perl configuration**
From the CPAN Testers report above (not my system):

```
Summary of my perl5 (revision 5 version 33 subversion 7) configuration:
   
  Platform:
    osname=cygwin
    osvers=3.1.7(0.34053)
    archname=x86_64-cygwin-thread-multi-quadmath
    uname='cygwin_nt-10.0 os-a01-l0123 3.1.7(0.34053) 2020-08-22 17:48 x86_64 cygwin '
    config_args='-de -Dmksymlinks -Dusedevel -Uinc_version_list -Uinstallusrbinperl -Dusethreads -Dusemultiplicity -Dusequadmath -Dprefix=/opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath -Darchname=x86_64-cygwin-thread-multi-quadmath'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags ='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_FORTIFY_SOURCE=2'
    optimize='-O3'
    cppflags='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion=''
    gccversion='7.4.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='__float128'
    nvsize=16
    Off_t='off_t'
    lseeksize=8
    alignbytes=16
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags =' -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base'
    libpth=/cygdrive/c/share/apps/gcc-7.4.0/cygwin-3-x86_64/bin/../lib/gcc/x86_64-pc-cygwin/7.4.0/include-fixed /cygdrive/c/share/apps/gcc-7.4.0/cygwin-3-x86_64/bin/../lib/gcc/../../lib /usr/lib /usr/lib/../lib/../include/w32api /lib
    libs=-lpthread -ldl -lquadmath
    perllibs=-lpthread -ldl -lquadmath
    libc=/usr/lib/libc.a
    so=dll
    useshrplib=true
    libperl=cygperl5_33_7.dll
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_QUADMATH
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under cygwin
  Compiled at Feb 25 2021 10:17:37
  %ENV:
    PERL5LIB="/opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib/site_perl:/opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib/perl5:/opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib"
    PERL5OPT=""
    PERL5_CPANPLUS_IS_RUNNING="29818"
    PERL5_CPAN_IS_RUNNING="29818"
    PERL_CPAN_REPORTER_CONFIG="/cygdrive/c/peter/.cpanreporter/config-cygwin-OS-A01-L0123.ini"
    PERL_EXTUTILS_AUTOINSTALL="1"
    PERL_MM_USE_DEFAULT="1"
    PERL_TEST_CRITIC="1"
    PERL_TEST_POD="1"
    PERL_USE_UNSAFE_INC="1"
  @INC:
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib/site_perl/5.33.7/x86_64-cygwin-thread-multi-quadmath
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib/site_perl/5.33.7
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib/site_perl
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib/perl5/5.33.7
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib/perl5/x86_64-cygwin-thread-multi-quadmath
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib/perl5
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib/5.33.7/x86_64-cygwin-thread-multi-quadmath
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib/5.33.7
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/local/lib
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/lib/site_perl/5.33.7/x86_64-cygwin-thread-multi-quadmath
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/lib/site_perl/5.33.7
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/lib/5.33.7/x86_64-cygwin-thread-multi-quadmath
    /opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/perl/5.33.7/x86_64-cygwin-thread-multi-quadmath/lib/5.33.7
    .
```

**Comment by hvds** [comment]
> **Description**
> PDL's recently-added use of `%+.17g` [...] is rejected as invalid on Perl 5.33.7 with quadmath.
[...]
> Since https://gcc.gnu.org/onlinedocs/gcc-9.3.0/libquadmath/quadmath_005fsnprintf.html has example code with `%+`, it seems the Perl function should not reject it out of hand.

I guess you are referring to this bit of the output in that test report; it would be useful to include it:
>  panic: quadmath invalid format "%+.17g" at /cygdrive/c/opt/perl5/cygwin_nt-10.0/3.1.7/x86_64/cpan/5.33.7/x86_64-cygwin-thread-multi-quadmath/build/PDL-2.029-0/blib/lib/PDL/Core.pm line 3090.

Strangely I've looked at that gcc doc before, but only read the spec:
> The function quadmath_snprintf converts a __float128 floating-point number into a string. It is a specialized alternative to snprintf, where the format string is restricted to a single conversion specifier with Q modifier and conversion specifier e, E, f, F, g, G, a or A, with no extra characters before or after the conversion specifier. The %m$ or *m$ style must not be used in the format. 

.. and never actually looked at the example code. My reading of the spec is that it is much stricter than the example code implies - that it permits as format string only strings like "%Qe", "%QF" with no other characters either inside or outside the single permitted directive. That leaves me wondering what on earth the spec actually _does_ mean.

My guess is that those that added or updated the Perl_quadmath_format_valid() check in the past read it the same way I did.

Maybe we'd be better off just doing a trial quadmath_snprintf() call, and rely on it to return -1 if it doesn't like the format.

**Comment by sisyphus** [comment]
It's the same problem with quadmath builds on Ubuntu and (native) Windows.
On a quadmath build, sv_setpvf() requires that the format be changed to "%+.17Qg".
Similarly, a long double build should have a format of "%+.17Lg".

Here's an Inline::C demo that works fine for me, irrespective of nvtype and nvsize.

```
use strict;
use warnings;

use Inline C => Config =>
  BUILD_NOISY => 1,
;

use Inline C => <<'EOC';

#if defined(USE_LONG_DOUBLE)
#define MY_FMT "%+.17Lg"
#elif NVSIZE == 8
#define MY_FMT "%+.17g"
#else
#define MY_FMT "%+.17Qg"
#endif

SV * foo3(SV * arg) {
  SV *sv ;
  sv = NEWSV(0, 19);
  sv_setpvf(sv, MY_FMT, SvNV(arg));
  return sv;
}

EOC

my $nv = sqrt 2;

my $x = foo3($nv);
print $x, " ", length($x), "\n";
``` 
On Ubuntu quadmath builds (but not Windows) that script compiles with a *warning* about "unknown conversion type character ‘Q’ in format", and some associated complaints, but it works fine and (importantly) avoids the panic attack.
I've raised the issue of that warning before, and I think @tonycoz felt that it was going to be a bit of a curly one to deal with.
(It's probably worth a second look.)

Anyway .... it seems that pdl.h needs some extra "case" statements to accommodate long double and __float128 builds.
Furthermore, it's unlikely that "17" is the correct value to specify for long double and __float128 precisions. It's much more likely to be "21" (for extended precision long doubles) and "33" (for __float128 and IEEE long doubles).

**Comment by sisyphus** [comment]
Minor correction - where I wrote "33", that should have been "36".

**Comment by mohawk2** [comment]
@sisyphus You're right that the numerical values won't be right for `long double`. This is because they're intended just for `double` (because PDL doesn't support `long double` yet). For `double` under quadmath, this Perl function seems to be breaking back-compatibility? That can't be the intention?

**Comment by sisyphus** [comment]
The troublesome code in pdl.h is:
```
sv_setpvf(outsv, "%.17g%+.17gi",creal(inany.value.C),cimag(inany.value.C));
```

I was of the opinion that the last 2 args must be NVs, whereas you've stated they are doubles.

So, I wrote the following script
```
use strict;
use warnings;

use Inline C => Config =>
  BUILD_NOISY => 1,
;

use Inline C => <<'EOC';

SV * foo() {
  SV *sv ;
  sv = NEWSV(0, 19);
  sv_setpvf(sv, "%+.17g", sqrt(2.0));
  return sv;
}

EOC

my $x = foo();
print "sqrt(2) is $x\n";
```
That should, of course, then run fine on a quadmath perl because the final arg supplied to sv_setpvf() is a double ... but it doesn't ... it produces the very same panic:
```
panic: quadmath invalid format "%+.17g" at try.pl line 21.
```
And, IMO, that's a bug in quadmath perl. (Surely, you should be able to assign a 'double' to an SV, even when nvtype is __float128 ?)

The preceding line in pdl.h contains:
```
sv_setpvf(outsv, "%.9g%+.9gi", crealf(inany.value.G),cimagf(inany.value.G));
```
From my testing, if that line ever gets executed on a quadmath perl, then the same panic will also be seen.
Is that so ?

**Comment by mohawk2** [comment]
> I was of the opinion that the last 2 args must be NVs, whereas you've stated they are doubles.

It's libm's documentation states that `creal` etc return doubles. I don't know why you're attaching that as my opinion :-D

> And, IMO, that's a bug in quadmath perl

That was my thought, too.

**Comment by tonycoz** [comment]
The problem here isn't that quadmath_format_valid() rejects the format, it's that the format is being checked at all.

The code in Perl_sv_catpvfn_flags() for quadmath seems to assume that all floats will be NVs, as if the code is only called with SVs.  A test that would catch this bug was disabled (`ext/XS_APItest/t/printf.t`).

I'll work on a fix.

**Comment by sisyphus** [comment]
On Sun, Mar 21, 2021 at 1:59 PM mohawk2 ***@***.***> wrote:

> I was of the opinion that the last 2 args must be NVs, whereas you've
> stated they are doubles.
>
> It's libm's documentation states that creal etc return doubles. I don't
> know why you're attaching that as my opinion :-D
>

Yeah - that came across as quite obtuse.
Initially, in some test subs I wrote, I noticed that
sv_setpvf(sv, "%+.17g", SvNV(arg));
 produced the error, but I didn't go the extra yards of noticing that the
sv_setpvf() usage in pdl.h was receiving a "double" arg, not an "NV" arg.
It was your statement " For double under quadmath, this Perl function seems
to be breaking..." that alerted me to the fact that the args were doubles,
not NVs.
And then I probably compounded the obtuseness by writing "whereas you've
stated" instead of  "whereas as you've stated".

I did take a look at how this bug was arising ... and the fix looked
non-trivial to me.
It's a good thing that Tony has stepped up.

**Comment by tonycoz** [comment]
> 
> 
> **Description**
> PDL's recently-added use of `%+.17g` (see https://github.com/PDLPorters/pdl/blob/dc5a0284c8d70dc03bf63506edb4c6b8b9b63977/Basic/Core/pdl.h.PL#L55) is rejected as invalid on Perl 5.33.7 with quadmath. This is especially regrettable since PDL doesn't yet fully support quadmath and long doubles, it's on the roadmap to do so, and this is a bit of a blocker.

As far as I can tell it's not the + causing the problem, the + is parsed correctly by sv_vcatpvfn_flags() and handled correctly (passed to the underlying snprintf() variant).

The problem is the quadmath code seems to have been written to only work with NVs (being a typedef for __float128), even in cases such as calls from XS/C where the  code should be able to pass in a double or long double.

quadmath_format_needed() checks whether there are *any* floating point formats in the string, and quadmath_format_valid() only accepts floating point formats that have the __float128 size flag, `Q`.  Combined these mean that correct code that supplies a double to a floating point specifier without a size flag is incorrectly rejected.

The code also failed in that it treats the long double flags (the ANSI C `L` and I don't know where it came from,`q`) as __float128 size indicators, so correct code that uses the ANSI C L indicator courts undefined behaviour if they use that and supply a long double.

I believe my change in #18658 fixes these problems.

While this will fix newer versions of perl, it won't help older versions, as a workaround for older perls I expect you'd need to always use NVs and the NV formats, eg:

```
sv_setpvf(outsv, "%.17" NVgf "%+.17" NVgf "i", (NV)creal(inany.value.C), (NV)cimag(inany.value.C));
```

Edit: add a missing quote to the workaround code

**Comment by mohawk2** [comment]
@tonycoz Thank you for taking the time on this!
