### ISSUE TITLE
[feature] create a Perl 7 project on this repo or the org repo

### ISSUE THREAD

**Issue by tisonkun** [Perl/perl5#18689]
Publicly showing what progress does "the Perl 7 project" is a net win. I found myself disappointing cannot catch up the progress from a easily accessed kanban and it is a risk more and more people remind of the days of Perl 6.

**Comment by tisonkun** [comment]
@briandfoy it seems we release 5.34 instead of 7 as a successor of 5.32 as announced before. Any progress on Perl 7 project?

**Comment by tisonkun** [comment]
Fine. I can see a gist from @Grinnz at https://gist.github.com/Grinnz/be5db6b1d54b22d8e21c975d68d7a54f

**Comment by leonerd** [comment]
My personal thoughts here [*] are that we'll just continue on the current path, of adding new features and changes, and making 5.xx releases, until some time when we think "youknow this has added quite a lot of stuff and is a nice set of changes since the days of 5.0, lets call it 7.0". The existing work on what might have been called "Perl 7" has already established that we can in fact bump the major version number - the technical internals are now fixed up to the point where this can actually happen.

Such changes we have right now:
 * **perl 5.32**: added the `isa` operator, and also we gained chained comparisons
 * **perl 5.34**: added `try/catch`
 * **perl 5.35** (which hopefully will become 5.36): added `defer {}`, bool as a real perl value type.
 * Still pending but I hope to get in before 5.36: `try/catch/finally`, string-vs-number as real stable values.

I have more vague plans and thoughts going out further towards 5.38, 5.40, etc... and at some point we probably just call that 7.0.

See also the ~40minute video at https://fosdem.org/2021/schedule/event/perl_in_2025/ but especially the final 5 minutes.

---

*: My personal thoughts, in that I am but one of the three current Perl Steering Committee members. Maybe the overall consensus of the committee and the wider core group would differ, these thoughts are simply my own.

**Comment by tisonkun** [comment]
Thank you so much for the information @leonerd ! I'm watching the video.

I highly appreciate your continuous works on moving Perl forward. The point I'm a bit confused is that if you're going to add new features and changes, we can always stay in Perl 5. For Perl 7, users may assume there is several breaking changes such as ever proposed default `strict`, `warning`, signature or sth.

**Comment by leonerd** [comment]
Indeed, that might be how we do it. Many of the newly-added features are currently by request only (e.g. `use feature 'try'`). Perhaps when we hit 7.0 that'll come as part of `use v7`:

```perl
use v7;  # might imply use feature 'try', 'defer', 'bool', ... 
```

Plus already right now `use v5.34` turns on `strict`, and as of v5.36 it'll turn on `warnings` as well, so we're already basically there.

**Comment by tisonkun** [comment]
Sounds promising.

I just notice that `use v5.x` is an explicit request for turning on several settings, like `use v5.10` turns on `say` (I love it).

In this way `use v7` may be unnecessary unless we'd like to make the interpreter default to `use v7`.

**Comment by Grinnz** [comment]
Changes to interpreter defaults outside of the normal deprecation and feature cycle are not planned.

**Comment by jkeenan** [comment]
Based on the responses to the OP provided by @leonerd and @Grinnz, I'm closing this ticket.  Whatever "Perl 7" becomes or whenever it comes into existence, it will almost certainly be an evolutionary process.  So we don't, at least at this time, need separate "Perl 7 project" pages in this repository.

Thank you very much.
Jim Keenan

**Comment by tisonkun** [comment]
Yes.

@jkeenan how do we use GitHub for Perl? I'm a bit unsure if such topics should be discussed on GitHub (Discussions?) or p5p mailing list.

**Comment by jkeenan** [comment]
> Yes.
> 
> @jkeenan how do we use GitHub for Perl? I'm a bit unsure if such topics should be discussed on GitHub (Discussions?) or p5p mailing list.

Speaking for myself here (and not for Perl 5 Porters in general), I'd say that before opening an Issue, one should inquire about the general status of the subject at hand, either via the mailing list or via irc.perl.org#p5p.  You would have gotten a (probably opinionated) update on what became of the Perl 7 project in 2020.  That would probably have led you to avoid creating an Issue.  The more exploratory your question is, the better it will be (IMO) to start it on those locations rather than as an issue or pull request.

**Comment by Grinnz** [comment]
This repo doesn't currently have github discussions enabled; the two places development of Perl is discussed are as mentioned above, here are some links:

* https://lists.perl.org/list/perl5-porters.html
* #p5p on http://www.irc.perl.org/
