### ISSUE TITLE
Here documents in regular expressions.

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18737]
Please make it possible to incorporate here documents in regular expressions as in:

```
say STDERR "aaa" =~ m(\A<<END\Z)x; #Bareword "END" not allowed
a*
END
```

**Comment by wchristian** [comment]
Is there a specific reason why this is not a sufficient solution?

https://perldoc.perl.org/perlre#/x-and-/xx

**Comment by hvds** [comment]
@Leont why did you close this? It would be helpful if you could comment when you do so, to explain your reasoning.

**Comment by xenu** [comment]
Perhaps he did this because this feature proposal is insane.

**Comment by hvds** [comment]
> Perhaps he did this because this feature proposal is insane.

If that were the case, then it should be stated somewhere that the ticket is "rejected because the feature proposal is insane". But there is no such statement, so this is just guesswork. If that was indeed the reason, ideally there would be some explanation of why it is insane.

I don't consider it insane, so if that were indeed the reason for closing it I would argue against it. But it's hard to argue against the lack of a reason.

**Comment by xenu** [comment]
If this ticket was created by anyone else I would've agreed with you. Unfortunately, philiprbrenan is a troll who [keeps on](https://github.com/Perl/perl5/issues?q=author%3Aphiliprbrenan) submitting weird, extremely low-effort feature requests. Those requests often involve making drastic changes to the language, for example: [removal of sigils](https://github.com/Perl/perl5/issues/17932) or [making semicolons optional](https://github.com/Perl/perl5/issues/17888). Their descriptions are always laconic and he never bothers to answer our questions about them.

Some contributors, including myself, are tired of his feature proposals. I don't blame @leont for not wanting to engage with this person.

**Comment by wchristian** [comment]
I'm not sure it's necessary to judge anyone's person.

I asked Philip to explain the reasoning and no answer was forthcoming, so the ticket was stalled.

**Comment by Leont** [comment]
> @Leont why did you close this? It would be helpful if you could comment when you do so, to explain your reasoning.

Because it only received negative feedback, and requests for more feedback were not responded too (something he consistently doesn't do).

And indeed given the large amount of low-effort proposals; he doesn't specify the use-case of this feature, nor does he explain how this is/isn't consistent with related features, nor does he specify how to handle the obvious backwards compatibility issues. Nor does he try to either learn how to implement these features, or to actively find someone to implement them. This is just dumping an idea on us and then moving on, and my patience with that ran out after the first dozen or so such proposals.

At this stage, I don't think it's reasonable to expect from us (p5p in general) to give all of these proposals a detailed response.

**Comment by hvds** [comment]
> At this stage, I don't think it's reasonable to expect from us (p5p in general) to give all of these proposals a detailed response.

I think we can and should be polite; they merit at least _a_ response even if not a particularly detailed one. This also serves as a record for anyone that finds this ticket back in the future.

> This is just dumping an idea on us and then moving on, and my patience with that ran out after the first dozen or so such proposals.

Concentrating your valuable efforts on those tickets for which you do have patience might then be more efficient.

**Comment by hvds** [comment]
> Please make it possible to incorporate here documents in regular expressions as in:
> 
> ```
> say STDERR "aaa" =~ m(\A<<END\Z)x; #Bareword "END" not allowed
> a*
> END
> ```

While this might make sense in the context of the language as a whole, supporting this would require defining `<` as a regexp metacharacter, necessitating a lengthy deprecation period and a lot of disruption for existing code.

You _can_ achieve the same effect by smuggling the here-doc in via variable interpolation:
```
say STDERR "aaa" =~ m{\A${\<<END}\Z}x;
a*
END
```

As such, the marginal benefits that we'd get from supporting heredocs directly don't seem sufficient to make up for the disruption involved in reclassifying `<`.
