### ISSUE TITLE
Modification of non-creatable array value detected at run time that could be detected at compile time

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18789]
Perl detects the following error at run time.  Might it be possible to detect it at compile time?

```
[]->[-1] = 1 # Modification of non-creatable array value attempted
```

**Comment by Grinnz** [comment]
So, this is detected at runtime because that is when it can determine there is no last element of the array, since it's empty. Detecting it at compile time could mess with autobox type behavior, so I'm not sure it's a good idea unless there's some common problem it would protect against.

**Comment by tonycoz** [comment]
We could detect that specific case, and some similar cases like `[ 1 ]->[-2] = 1` at compile-time, like the `each({})` warning in #18643, but it doesn't strike me as code that a programmer is likely to produce, and unlike the `each({})` code it produces a fairly noisy runtime error, which makes it easy to see what's wrong.

(an aside: autobox's implementation looks unsafe, making updates to PL_check at each entry to/exit from the autobox scope, rather than updating it once and depending on %^H)

**Comment by Leont** [comment]
Yeah, it seems like a rather unlikely thing for a developer to do
