### ISSUE TITLE
__PACKAGE__ in sub names

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18816]
Declaring a sub with ```__PACKAGE__``` in the name is permissible but has surprising results:
```
package AAA;

sub __PACKAGE__::DDD::ddd() {say STDERR "ddd"}  # permissible

__PACKAGE__::DDD::ddd();  # ddd

AAA::DDD::ddd();          # Undefined subroutine &AAA::DDD::ddd called
```

**Comment by Grinnz** [comment]
This is normal. `__PACKAGE__::DDD` is a valid package name, and nothing in these statements resolve the `__PACKAGE__` symbol.

**Comment by Grinnz** [comment]
Named subroutines cannot contain a dynamic name. To assign a sub to a dynamic name slot, you must turn off strict refs:

```
no strict 'refs';
*{__PACKAGE__ . '::DDD::ddd'} = sub { ... };
```

But this is usually pretty pointless since the package declaration is lexical, so you will always know what `__PACKAGE__` contains, except in generated code.

To call it, you can use UNIVERSAL::can:

```
(__PACKAGE__ . '::DDD')->can('ddd')->();
```
