### ISSUE TITLE
Use strict does not warn about attempts to do array arithmetic

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#19071]
Please make **use strict** warn about attempts to do arithmetic on array references.

use strict;
say STDERR  [1] + [2];   # 188385713997216

**Comment by Corion** [comment]
The `strict` pragma does not issue warnings. It prohibits operations or enforces declarations.

If you intend this as a feature request, please consider following the RFC process as discussed at https://www.nntp.perl.org/group/perl.perl5.porters/2021/06/msg260336.html instead of rapid-fire posting bug reports.

**Comment by leonerd** [comment]
Addition adds numbers. Plain references yield their refaddr when used numerically. This is all documented and self-consistent.

I will remind you of Leon T's recent comment, that the Perl5 github issues list is not a help channel.
