### ISSUE TITLE
pkg->can() should return false/undef if the slot is declared but uninitialized (or DUMMY).

### ISSUE THREAD

**Issue by EvanCarroll** [Perl/perl5#19366]
This bug report is [inspired by this question on StackOverflow, _"Why is `*main::my_func{CODE}*` a coderef when function `my_func()` is exported but not defined?"_](https://stackoverflow.com/q/70834431/124486).

Currently when you run `sub foo` or Exporter with an undefined sub what happens is a DUMMY sub is inserted into the slot. This is fine, however it seems no reasonable person will expect `->can()` to return a reference to a DUMMY sub that triggers a runtime error.

```perl
use strict;
use warnings;

{
    package MyPackage;
    use parent 'Exporter';
    our @EXPORT = qw(foo);
}

MyPackage->import();
if ( MyPackage->can('foo') ) {
	MyPackage->can('foo')->();
}
```

I would suggest having `->can()` here return undef, as if the sub didn't even exist. Alternatively, perhaps in boolean context `can` can return `false` here?

**Comment by ikegami** [comment]
> I would suggest having `->can()` here return undef

I don't think `can` should be changed. It returns the sub that would be called if you called `$o->foo`, just like it should.

But Exporter shouldn't be creating subs that don't exist. At the very least, it should warn.

**Comment by ikegami** [comment]
That raises the question: What about scalars, arrays and hashes that don't exist? What should Exporter do about those?

**Comment by EvanCarroll** [comment]
I don't think `->can` should return the function that _would_ be called. That's certainly not what it's documented to do anyway,

> _`$obj->can( METHOD )` `CLASS->can( METHOD )` `eval { VAL->can( METHOD ) }`  **`can` checks if the object or class has a method called "METHOD"**. If it does, then it returns a reference to the sub. If it does not, then it returns `undef`. This includes methods inherited or imported by `$obj`, "CLASS", or "VAL"._

I would not say a placeholder sub is "imported" or "inherited." It's an implementation detail and I don't think it helps anyone to continue this behavior. Is there any benefit that I'm missing? When would a user want to know if there was a dummy sub that did nothing except print a warning that the slot is undefined?

> If [a class] does not [have a method], then it returns `undef`

Means you have to think of DUMMY sub as a method. Do people conceptualize them like that?

**Comment by ikegami** [comment]
> I don't think `->can` should return the function that _would_ be called. That's certainly not what it's documented to do anyway,

That what it does, and that's what it's documented to do: "`can` checks if the object or class has a method called `METHOD`. If it does, then it returns a reference to the sub" To argue otherwise is to argue that `$o->METHOD` does something other than call the method `METHOD`.

But terminology aside, it's clear it abides by its documentation. And I fully support its documented behaviour.

**Comment by ikegami** [comment]
> Means you have to think of DUMMY sub as a method

Yes, I think that when you declare a sub, you have a sub. That's the whole point of a declaration. Even `exists` claims that the sub exists.

This isn't a problem with `exists` and `->can`.  Again, the issue is that a sub was unintentionally declared. And that's what should be fixed. `exists` and `->can` shouldn't be blamed for accepting the declaration at face value.

**Comment by ikegami** [comment]
oh, and I don't know what you keep calling it a "DUMMY sub". It's not a placeholder that gets replaced once you define it. It's still the same sub after you provide the definition.

```
$ perl -M5.010 -e'
   sub f;
   BEGIN { $r = \&f; }
   BEGIN { say $r; }
   sub f { say "ok" }
   say $r;
   $r->();
'
CODE(0x559e386a9fb8)
CODE(0x559e386a9fb8)
ok
```

**Comment by EvanCarroll** [comment]
> That what it does, and that's what it's documented to do: "can checks if the object or class has a method called METHOD. If it does, then it returns a reference to the sub" To argue otherwise is to argue that $o->METHOD does something other than call the method METHOD.
> 
> But terminology aside, it's clear it abides by its documentation. And I fully support its documented behaviour.

I asked one question.

You want the behavior of `can` to mirror `exist` as it currently does, but it's not clear _why_ you would desire that behavior. Exists can test whether or not a package symbol _exists_; `can` tests whether or not it can invoked as a method. If it is undefined, it can not be invoked without generating an error. Of what utility is it to return a reference to something that can not be invoked without generating an error? Why would a user want this?

**Comment by oodler577** [comment]
>You want the behavior of can to mirror exist as it currently does, but it's not clear why you would desire that behavior. Exists can test whether or not a package symbol exists; can tests whether or not it can invoked as a method. If it is undefined, it can not be invoked without generating an error.

The following seems relevant and hopefully helps shed some like on what seems like the underlying root cause of whatever behavior you're concerned about.

- https://www.perl.com/pub/2005/03/17/symtables.html/
- https://en.wikipedia.org/wiki/Autovivification
- https://perldoc.perl.org/perlmod#Symbol-Tables

Note,

```
Symbol Tables
The symbol table for a package happens to be stored in the hash of that name with two colons appended. The main symbol table's name is thus %main::, or %:: for short. Likewise the symbol table for the nested package mentioned earlier is named %OUTER::INNER::.
```

> Of what utility is it to return a reference to something that can not be invoked without generating an error?

`UNIVERSAL::can` is only reporting what's in the symbol table, not what happens when you actually call it. Also note from teh docs:

> `can` cannot know whether an object will be able to provide a method through AUTOLOAD (unless the object's class has overridden can appropriately), so a return value of undef does not necessarily mean the object will not be able to handle the method call. 

Which seems like the same problem, but from the other perspective. 

This is what autovivication referes to, avoids the need for the programmer to predeclare things in hashs and arrays, (wikipedia):

> In the Perl programming language, autovivification is the automatic creation of new arrays and hashes as required every time an undefined value is dereferenced. Perl autovivification allows a programmer to refer to a structured variable, and arbitrary sub-elements of that structured variable, without expressly declaring the existence of the variable and its complete structure beforehand.[1]

> Why would a user want this?

Answered above, could be handy and `can` is not suitable to be the only check you make. Are you messing with the symbol table or using `AUTOLOAD`? You might have some kind of decision problem to deal with.

> to refer to a structured variable, and arbitrary sub-elements of that structured variable, without expressly declaring the existence of the variable and its complete structure beforehand.

**Comment by ikegami** [comment]
Because it makes absolutely no sense for `can` to ignore an existing method.

Do you also think `$o->foo` should ignore existing-but-not-defined methods?

**Comment by ikegami** [comment]
> it's not clear why you would desire that behavior

Because it makes absolutely no sense for `can` to ignore an existing method. It's not clear why would think it would make sense for them not to. 

First of all, it t makes no sense for `$o->can('foo')->()` to do something different than `$o->foo()`. They should both call the method if it exists. Do you think `$o->foo` should ignore existing-but-not-defined methods too?

Secondly, if someone declares a sub and attempts to call it, what's more likely? That both the declaration and the call were erroneous, or that a definition was missing. Why should `->can` assume the least likely scenario?

**Comment by ikegami** [comment]
> it's not clear why you would desire that behavior

Because it makes absolutely no sense for `can` to ignore an existing method. It's hard to answer because it's not clear why would think it would make sense for it to not return the existing sub.

For starters, it makes no sense for `$o->can('foo')->()` to do something different than `$o->foo`. Take a class with `sub DOES;`, for example. It doesn't make sense for `$o->can('DOES')` to return `\&UNIVERSAL::DOES` if `$o->DOES` doesn't call `UNIVERSAL::DOES`, and it doesn't make sense for `$o->can('DOES')` to return `undef` for a method every object has.

Maybe you think `$o->foo` should ignore existing-but-not-defined subs too. But that would mean you think it's almost guaranteed that someone accidentally included both a declaration for a sub that shouldn't exist *and* a call to that same sub. But I find that to be far from the truth. People rarely declare subs by accident, they rarely call subs by accident, and they even more rarely do both! Errors as simple and common as typos in sub names and forgetting to load a file shouldn't be silently ignored!

**Comment by ikegami** [comment]
> But Exporter shouldn't be creating subs that don't exist. At the very least, it should warn.

...but it's too late for that. Starting to requiring modules to declare exports would break modules such as users of AutoLoader.

**Comment by dboehmer** [comment]
Could `Exporter` issue a warning if exports are not defined and the exporting package has no `AUTOLOAD` function?

**Comment by EvanCarroll** [comment]
`DOES` unlike an undefined sub that's installed with `sub` or `Exporter` is actually useful. It works just fine.

```
$ perl -E'say main->can("DOES")->("main", "UNIVERSAL")'
1
```

If that didn't work -- if either `DOES` was not a method or it was a method that as a mere implementation detail threw an identical error that a method was not installed (however you want to cut it) -- then I would argue that `->can("DOES")` should not return the reference to that sub. But as is, it is actually a meaningful method. Unlike the one in the slot that `sub foo` or Exporter installs.

Put another way a method is not  "undefined" or "not able to be located": it's a defined thing that can be invoked and called and that's what all the docs and all the users refer to it as. This is why `can` should not return a reference to it.

```sh
$ perl -E'sub foo; main->bar;'
Can't locate object method "bar" via package "main" at -e line 1.
$ perl -E'sub foo; main->foo;'
Undefined subroutine &main::foo called at -e line 1.
```

You're defining the utility in terms of the current implementation rather than a use case.

**Comment by ikegami** [comment]
> If either DOES was not a method

`DOES` is a method of every object

```
$ perl -e'bless({})->DOES("foo"); print "ok\n"'
ok
```

> If that didn't work

It wouldn't work with your change.

> You're defining the utility in terms of the current implementation rather than a use case.

No

**Comment by ikegami** [comment]
> If either DOES was not a method

`DOES` is a method of every object, just like `can` and `isa`.

```
$ perl -e'bless({})->DOES("foo"); print "ok\n"'
ok
```

> If that didn't work

It wouldn't work with your change. `can` could return `undef` for `DOES` even though it's a method of every object.

> You're defining the utility in terms of the current implementation rather than a use case.

No. Two use cases your change would break were given.

Perhaps you're referring to the underlying presumption that declaring subs is useful. But that's not relevant. If they weren't, the solution would be to remove that feature, not change `can`. So that doesn't help your case either.

Anyway, you're deflecting. You still haven't given a reason why would think it would make sense for it not to return the existing sub. All you've said is that no reasonable person would expect anything but your changed behaviour, while that's clearly not true.  We're already shown that it would directly break an existing feature, it would break existing code, and it would hide errors making them harder to find and debug.

**Comment by ikegami** [comment]
> it's a defined thing that can be invoked and called and that's what all the docs and all the users refer to it as.

No, that's not true. If ModB didn't have a method named `f`, the following would print `ok`.

```
$ perl -e'
   { package ModA; sub f { print "ok\n" } }
   { package ModB; @ISA = "ModA"; sub f; }
   ModB->f()
'
Undefined subroutine &ModB::f called at -e line 5.
```

Perl obviously thinks ModB has a method named `f`. The ability to declare subs without defining them is a feature of Perl. You've been pretending that this is not the case and that `can` is broken since the start, but breaking `can` is not the answer to not liking that feature.

Use `defined(&$sub)` to check if the method isn't defined.

**Comment by EvanCarroll** [comment]
Well, that's easy then. So the reason _why_ a user needs to know if an undefined function exists on a slot that can otherwise **not** be invoked without error is because without it the user would not know if a method call has resolved or not.

I agree then with the statement,

> The ability to declare subs without defining them is a feature of Perl [...] is not the answer to not liking that feature.

That's correct. I just don't like that feature. I can't think of any case I would want to occupy a slot and obscure method resolution when the underlying function itself can not be invoked.

**Comment by dboehmer** [comment]
> Could `Exporter` issue a warning if exports are not defined and the exporting package has no `AUTOLOAD` function?

@EvanCarroll What about my suggestion?

**Comment by EvanCarroll** [comment]
@dboehmer I think it's an improvement. But to be honest it's not a major thing. It doesn't get me excited. The real problem that I see is that we have a "feature" to _have_ an undefined function (which can't be invoked without error) which doesn't seem to have any utility from the user's perspective, but because we have it and because it has obvious implications on method resolution (that I overlooked), we **need** to have a feature to know whether an object has this function and we're using `->can` for that.

That whole system is pretty silly from my perspective. I mean in C, the reason why you can declare an undefined function is because there is obvious type checking. But Perl doesn't have that. Perl does have prototypes -- is that why this exists? If so, why allow a function **without** a definition that does not have a prototype? And why should an undefined function stop method resolution? Why not put the `defined` test there and reduce the complexity facing the user? Anyway, [I asked a follow up question mostly for my own curiosity](https://stackoverflow.com/q/70868805/124486)

**Comment by oodler577** [comment]
@EvanCarroll I think it'd be beneficial to you to couch this as an autovivified hash key that's set to `undef`. You could just as well check if this key in the symbol table exists but is not defined. Could this lead to confusion? Yes, but `can` already has the qualification that it won't "find" methods if `AUTOLOAD` is defined; it's the reverse issue. So perhaps the right fix is to add this additional qualification in the perldoc for `UNIVERSAL::can` and any other introspective methods it may present.

**Comment by EvanCarroll** [comment]
@oodler577 It's not clear to me at all why you think of this as autovivification or what you think the connection to the two is. Autovivification grants you the ability in runtime to treat something that doesn't exist as it if it did exist. Namely that a slot in a hash or array is _already_ an array or hash when you dereference it as such without having to declare it as such. I don't see the connection between that and this topic.

I also grant you that `AUTOLOAD` stops UNIVERSAL's `can` implementation from being complete. But that's a caveat with `AUTOLOAD`. The solution there is **do not use `AUTOLOAD`** (which is what most users do). I don't see this as a "reverse" issue. This is an effect that stops `can` from functioning as intended **without** `AUTOLOAD`.

**Comment by oodler577** [comment]
I was hoping to provide some closure, not open up a new can of worms. If you're cool with, _Not using `AUTOLOAD`_; then you should be cool with _Not using `Exporter`_. Nonetheless, it seems to be an issue of "a hash key coming to life (vivication)" - usually _automatically_. And this is why I think it'd be helpful to have this in mind when considering what `can` does do versus what it would do if _autovivication_ was not a thing in Perl.
