### ISSUE TITLE
Enh. request: Catch @{ bareword[index] } as invalid else update docs

### ISSUE THREAD

**Issue by jimav** [Perl/perl5#19497]
This may not be a bug, but rather a documentation problem.  Or a user problem...

Is `@{ bareword[index] }` intended to be valid syntax?   I couldn't find in _perlref_ an explanation of what such a construct means.

In fact it is accepted (in v5.30.0) and means an array slice, more conventionally written as
`@{arrayname}[index]` or just `@arrayname[index]`.

If the former is not correct syntax, then it would be great if perl could catch it, so as to save users from silent bugs if they have a typo like in the following:
```
use strict; use warnings;
my @aryofarys = ([]);
# ...
@{  aryofarys[0] } = (1,2,3);
#  ^typo omitting the $ sigl
```
On the other hand if `@{ name[index] }` is correct syntax, then perhaps  _perlref_ could be augmented in the "barewords" discussion to point out its intended meaning; or the "slices" discussion in _perldata_.

**Comment by Grinnz** [comment]
I believe there's a previous issue discussing this syntax but can't find it

**Comment by xenu** [comment]
https://github.com/Perl/perl5/issues/18800

**Comment by demerphq** [comment]
On Sat, 5 Mar 2022 at 21:13, Jim Avera ***@***.***> wrote:
>
> This may not be a bug, but rather a documentation problem. Or a user problem...
>
> Is @{ bareword[index] } intended to be valid syntax? I couldn't find in perlref an explanation of what such a construct means.

Yes it is. It is the demarcated version of a variable name. Eg,
strings are demarcated, we have a symbol to show where the start and
stop. So are array subscripts and hash subscripts.  Perl allows you to
use implicitly delimited variable names, eg where you have whitespace
or other non-variable letter syntax following the variable name, but
the syntax is especially dangerous in interpolation where such
constraints are not necessarily in place. Even in normal code there
are places where you MUST delimit your variable name with a space, eg,
consider:

sub func { return "blah" }
print $fh func;

if you were to remove the space between $fh and func() it would become
a reference to a different variable $fhfunc.

This is especially troublesome in interpolation.

Demarcated variable names are the solution. You can inject a
demarcated variable into any non variable containing string without
changing the meaning of the variable name. You can also remove nearly
all the spaces from a program if you ONLY use demarcated variable
names.

Consider the string "[0]"

If I stick $array[0] at the start of that string I will turn it into
$array[0][0].

"$array[0][0]" would NOT mean $array[0] . "[0]".

If I stick ${array[0]} at the start of that variable then it will
still be referring to $array[0] and it will be equivalent  to
$array[0] . "[0]".

This is the same reason we add \g{...} to the regex engine, because
concatenating \1 into an existing string or pattern starting with
digits would change its meaning. So we offer a demarcated version
instead.

It is actually *required* syntax for interpolating caret array names
like @{^CAPTURE}. If you want to interpolate ${^CAPTURE}[0] you MUST
write it as ${^CAPTURE[0]}.  Writing ${^CAPTURE}[0] in a string will
parse as ${^CAPTURE} . "[0]".

> In fact it is accepted (in v5.30.0) and means an array slice, more conventionally written as
> @{arrayname}[index] or just @arrayname[index].

The slice form is just a natural extension of the general concept of
demarcated variable names.

> If the former is not correct syntax, then it would be great if perl could catch it, so as to save users from silent bugs if they have a typo like in the following:
>
> my @aryofarys = ([]);
> # ...
> @{  aryofarys[0] } = (1,2,3);
> #  ^typo omitting the $ sigl
>
> On the other hand if @{ name[index] } is correct syntax, then perhaps perlref could be augmented in the "barewords" discussion to point out its intended meaning;

I can look at a patch for that. But it is definitely intentional.

cheers,
Yves
-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
On Sun, 6 Mar 2022 at 09:04, demerphq ***@***.***> wrote:
> Demarcated variable names are the solution. You can inject a
> demarcated variable into any non variable containing string without
> changing the meaning of the variable name.

I worded that a little clumsily. I meant to say "You can inject a
demarcated variable ANYWHERE into any non variable containing string
without changing the meaning of the variable name." The reason I said
"non variable containing" is purely that if you injected ${foo[10]}
into the middle of "$foo" it would change the meaning of $foo. My
point here is that if you operate with demarcated variable names you
avoid a bunch of issues with concatenation that would come up if you
use implicitly delimited variable names. Of course, implicitly
delimited variable names are the norm, and generally people think
putting whitespace in a program is a *good* thing, but in some edge
cases, like interpolation, it can be awkward to do. You might have to
change the rest of the string. Eg, instead of writing "${foo[10]}[10]"
you could write "$foo[10]\[10]", and likely most people do actually
use the backlash. But that is more complex for something like a code
generator than just using the demarcated form.

cheers,
yves
-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by jimav** [comment]
> instead of writing "${foo[10]}[10]" you could write "$foo[10]\[10]", and likely most people do actually use the backlash. But that is more complex for something like a code generator than just using the demarcated form.

Sounds like this "_demarcated form_" syntax is what needs to be documented.  Currently it is isn't at least not using that term.   

What is confusing is the docs imply that if the 'what' in `{what}` isn't a bareword it must be valid Perl expression syntax yielding a ref.  Confusing since `foo[10] `is not a valid expression elsewhere (AFAICT).
```
zgrep -i demarcated /usr/share/man/*/perl*
<no results>
```

**Comment by demerphq** [comment]
On Sun, 6 Mar 2022 at 09:25, Jim Avera ***@***.***> wrote:

> instead of writing "${foo[10]}[10]" you could write "$foo[10][10]", and
> likely most people do actually use the backlash. But that is more complex
> for something like a code generator than just using the demarcated form.
>
> Sounds like this "*demarcated form*" syntax is what needs to be
> documented. Currently it is isn't at least not using that term:
>
> zgrep -i demarcated /usr/share/man/*/perl*
> <no results>
>
>
That doesn't surprise me, I was trying to find the correct counterpoint to
delimiting. In the context of data most folks would say "quoted", and in a
sense this is a form of quoting. demarcated however is the dictionary term
that matches most closely to the concept.

I'll write up a doc patch in a bit.

Like I said, we have introduced new features exactly to provide
demarcated forms of some of our constructs over the years for
various reasons, \x{...} and \g{...} are good examples.

cheers,
Yves

**Comment by demerphq** [comment]
On Sun, 6 Mar 2022 at 09:36, demerphq ***@***.***> wrote:
>
> On Sun, 6 Mar 2022 at 09:25, Jim Avera ***@***.***> wrote:
>>
>> instead of writing "${foo[10]}[10]" you could write "$foo[10][10]", and likely most people do actually use the backlash. But that is more complex for something like a code generator than just using the demarcated form.
>>
>> Sounds like this "demarcated form" syntax is what needs to be documented. Currently it is isn't at least not using that term:
>>
>> zgrep -i demarcated /usr/share/man/*/perl*
>> <no results>
>
>
> That doesn't surprise me, I was trying to find the correct counterpoint to delimiting. In the context of data most folks would say "quoted", and in a sense this is a form of quoting. demarcated however is the dictionary term that matches most closely to the concept.
>
> I'll write up a doc patch in a bit.

Pushed as https://github.com/Perl/perl5/pull/19500

Yves
-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
Doc fix merged.
