### ISSUE TITLE
Triple derefences work with scalars but not subs

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#19774]
Perl does seems to allow triple de-references in some situations, but not all as shown below where **$$$** works but **&&$** does not.  Might it be possible to allow such de-references to occur reliably in any combination? 

```
use v5.30;
my $s = sub {sub{say "AAA"}};
say &$s;     # CODE(0x5622e61fb4b8)
say &{&$s};
say &$s->&*;
say &&$s;    # Useless use of private variable in void context

say $$$s;

&$s;
&{&$s};
&$s->&*;
&&$s;        # syntax error
```

**Comment by Leont** [comment]
No, this is not easily possible using prefix syntax because `&&` already is an operator of its own. Note that you probably shouldn't dereference coderefs with `&`/`->&*` because that has `&sub` semantics (it passes on @_ as args). You really should be using `->() ` instead to avoid nasty surprises. Most people would consider that more readable too.
