### ISSUE TITLE
BBC: Blead Breaks Devel::FindPerl

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#19804]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.42 running under perl 5.37.1.

-----------------------------------------------------------------
[Please describe your issue here]

BBC: Blead Breaks Devel::FindPerl

Please see http://matrix.cpantesters.org/?dist=Devel::FindPerl

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.37.1:

Configured by cpan at Sun May 29 03:22:56 EDT 2022.

Summary of my perl5 (revision 5 version 37 subversion 1) configuration:
  Commit id: 66673af5955ecc69305b0baad0a8fb6162312409
  Platform:
    osname=linux
    osvers=5.15.40-0-lts
    archname=x86_64-linux-thread-multi
    uname='linux cjg-alpine3 5.15.40-0-lts #1-alpine smp wed, 18 may 2022 08:12:19 +0000 x86_64 linux '
    config_args='-des -Dprefix=~/bin/perl-blead -Dscriptdir=~/bin/perl-blead/bin -Dusedevel -Duse64bitall -Duseithreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='10.3.1 20211027'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib /lib
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.37.1:
    /home/cpan/bin/perl-blead/lib/site_perl/5.37.1/x86_64-linux-thread-multi
    /home/cpan/bin/perl-blead/lib/site_perl/5.37.1
    /home/cpan/bin/perl-blead/lib/5.37.1/x86_64-linux-thread-multi
    /home/cpan/bin/perl-blead/lib/5.37.1

---
Environment for perl 5.37.1:
    HOME=/home/cpan
    LANG=C.UTF-8
    LANGUAGE (unset)
    LC_COLLATE=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl-blead/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

**Comment by hvds** [comment]
@Leont this looks to be because `Devel::FindPerl::_capture_command()` unsets `$ENV{PATH}`.

@demerphq I'm beginning to think maybe we should consider special handling for an empty PATH, perhaps by identifying a random string that points to a non-existent path and silently setting PATH to that. I reckon it has been _good practice_ for a long time to do `local $ENV{PATH}`, so this is going to affect a lot of both CPAN and darkpan.

**Comment by jkeenan** [comment]
Bisecting with the following invocation:
```
perl Porting/bisect.pl --start=v5.36.0 \
--end=704ee149f702a507eec39e99c71a91932da3922b \
--module=Devel::FindPerl
```
... points to this commit:
```
92ec2fce1aace295365d7d86c61c98df8202fc9d is the first bad commit
commit 92ec2fce1aace295365d7d86c61c98df8202fc9d
Author: Yves Orton <demerphq@gmail.com>
Date:   Wed Apr 20 06:55:45 2022 +0200
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Sat May 28 15:01:00 2022 -0600
```
@demerphq @khwilliamson Can you take a look?

**Comment by haarg** [comment]
This has been fixed in Devel-FindPerl-0.016

**Comment by demerphq** [comment]
On Wed, 1 Jun 2022 at 05:47, Hugo van der Sanden ***@***.***>
wrote:

> @Leont <https://github.com/Leont> this looks to be because
> Devel::FindPerl::_capture_command() unsets $ENV{PATH}.
>
> @demerphq <https://github.com/demerphq> I'm beginning to think maybe we
> should consider special handling for an empty PATH, perhaps by identifying
> a random string that points to a non-existent path and silently setting
> PATH to that. I reckon it has been *good practice* for a long time to do local
> $ENV{PATH}, so this is going to affect a lot of both CPAN and darkpan.
>
FWIW, I dont think that is as straightforward as it sounds. Consider, we
decide to use "/perl_temp_dir_does_not_exist" as a replacement for the
empty path.  This then becomes an attack vector on scripts running under
-T. We could create a private temporary directory and then use its path as
the replacement, but it doesn't sound ideal either. [1]

I am not sure what we can do to make this less painful.

The basic problem seems to be that when the -T behavior regarding "." was
introduced no-one realized that "" has the same meaning.

It feels to me that the only thing we can do here to make this better is to
change the approach. Instead of making the %ENV tied hash detect bogus data
on STORE operations, make it so that when we execute a function which
depends on $ENV{PATH} we check the PATH and if it is empty or if it
contains empty elements, then throw an exception if a non-fully qualified
path is passed into such functions.  Could be a fair bit of work to make it
happen though. And it might open up other security holes we haven't thought
about.

[1] After writing most of this mail it occurred to me that maybe we could
use "..." as a replacement for the empty directory, as I think it should be
impossible to create such a directory.  If so then it renders my other
comments in this mail moot.

cheers,
Yves


--
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by haarg** [comment]
PATH does not need to be set to a path that does not exist, or a temp directory. It can simply be deleted.

**Comment by demerphq** [comment]
On Tue, 12 Jul 2022 at 09:58, Graham Knop ***@***.***> wrote:

> PATH does not need to be set to a path that does not exist, or a temp
> directory. It can simply be deleted.
>
Even better. I /thought/ I had checked that in the past and it didn't work,
but checking now it does. Could there be an edge case where that
isn't sufficient?

cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by haarg** [comment]
The only real edge case I can think of is if some later code naively tries to add to PATH doing something like `PATH="/my/path:$PATH"` it will end up with an empty path as one of the entries.

**Comment by demerphq** [comment]
On Tue, 12 Jul 2022 at 11:11, Graham Knop ***@***.***> wrote:

> The only real edge case I can think of is if some later code naively tries
> to add to PATH doing something like PATH="/my/path:$PATH" it will end up
> with an empty path as one of the entries.
>
 And under taint /that/ would throw an exception which is what we would
want. Seems good to me. Thanks for the catch.

cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"
