### ISSUE TITLE
perldelta for 5.37.1

### ISSUE THREAD

**Issue by sigzero** [Perl/perl5#19880]
**Where**
In the perldata for 5.37.1 is says in the second sentence:

If you are upgrading from an earlier release such as 5.36.0, first read [perl5370delta](https://metacpan.org/pod/perl5370delta), which describes differences between 5.36.0 and 5.37.0.

**Description**
perl5730delta is a bad link. That file does not exist.

**Comment by Grinnz** [comment]
It does exist. It's just not indexed on metacpan because no stable releases of Perl have included the file. It's a metacpan bug that the interlink does not link to the same unindexed distribution (https://github.com/metacpan/metacpan-web/issues/2681). Use perldoc.perl.org to see the proper installed versions of documentation with interlinks: https://perldoc.perl.org/5.37.1/perldelta
