### ISSUE TITLE
remove username from repo

### ISSUE THREAD

**Issue by ghost** [Perl/perl5#20010]
I want to have my name, e-mail address and username, removed from the repo.

affected files

.mailmap
AUTHORS
Porting/checkAUTHORS.pl

Would a PR removing the relevant lines suffice, or if any of the above files are auto generated, and would be recreated, are there special instructions to remove the relevant lines?

If special instructions are indicated please provide these.

**Comment by Leont** [comment]
Given two of those are generated from git history, it's currently not possibly. But I guess it could be made possible (by using a hash of some sort to filter you out).

@demerphq ideas?

**Comment by ghost** [comment]
I neglected to mention the file pod/perl5340delta.pod.

**Comment by ghost** [comment]
Presently there are no commits to the repo, consequently no git history, associated with this username.

`https://github.com/Perl/perl5/commits?author=`

Perhaps a Contributor would oblige and remove these lines, which would not result in a git history associated with this username.

**Comment by rwp0** [comment]
@apparluk Sorry, but why would you like to remove your name from the authors?

**Comment by Leont** [comment]
> Perhaps a Contributor would oblige and remove these lines, which would not result in a git history associated with this username.

Like I said before, `.mailmap` and `AUTHORS` are generated files, so there's no point to manually removing them: they'd be added back on regeneration.

`Porting/checkAUTHORS.pl` is the source of the link between the two addresses, I'm not sure we can remove that without things breaking. I suspect we need to block your email first if we don't want to break tests.

The `perl5340delta` entry can be fixed easily enough though.

**Comment by ghost** [comment]
Update nmake for VS 2017  
committed on Jun 14, 2017

I don't think there's any code I wrote in the repo since then.

**Comment by Leont** [comment]
b998bd1a4a2c4e35a119ea73c7650a26e0060950

**Comment by ghost** [comment]
If removal of the content it is too much trouble, I could just use a different GitHub account and e-mail address.

I presume in the foregoing that a merged commit - using a different GitHub account and e-mail address - would overwrite the current information in .mailmap, AUTHORS and Porting/checkAUTHORS.pl.

**Comment by Leont** [comment]
> If removal of the content it is too much trouble, I could just use a different GitHub account and e-mail address.

I'm sure it can be done, but it requires code and someone will need to write that first.

> I presume in the foregoing that a merged commit - using a different GitHub account and e-mail address - would overwrite the current information in .mailmap, AUTHORS and Porting/checkAUTHORS.pl.

I'm not sure what you mean with that. What would a merged commit have to do with it? And no information would be overwritten in .mailmap, it only gets information added (AUTHORS we can redirect using Porting/checkAUTHORS.pl).

**Comment by ghost** [comment]
> not sure what you mean

my misunderstanding

Where a Committer has used more than one e-mail address multi-line Committers' entries appear in `Porting/checkAUTHORS.pl`, and, like you indicated before git history plays a role in generation of two repository files, so, using a different GitHub account and e-mail address wouldn't result in overwriting `.mailmap` and the old content would remain in `Porting/checkAUTHORS.pl`.

**Comment by demerphq** [comment]
On Sun, 31 Jul 2022, 21:28 apparluk, ***@***.***> wrote:

> not sure what you mean
>
> my misunderstanding
>
> Where a Committer has used more than one e-mail address multi-line
> Committers' entries appear in Porting/checkAUTHORS.pl, and, like you
> indicated before git history plays a role in generation of two repository
> files, so, using a different GitHub account and e-mail address wouldn't
> result in overwriting .mailmap and the old content would remain in
> Porting/checkAUTHORS.pl
>

Forget checkAUTHORS. It is not your problem to solve.

The fundamental problem is you created a patch which added yourself to
AUTHORS and added a github user id to the list of committers.

We can arrange to remove the AUTHORS entry, and we can set up .mailmap to
cause your details to be hidden on github and in casual use of git tooling,
however doing so means the github email will remain in .mailmap.

Or we can remove you entirely from the files you stated but then your email
will be visible in git log and on github.

Doing the former will take me a few minutes  doing the latter will be more
effort. I am fine with either. Just let me know.

The only way we can remove all trace is to rewrite the repo, if you want
that it needs to handled by the PSC, and personally I'd recommend reading
up on the Streisand effect before you ask for that. It might produce exact
opposite of the desired effect.

As long as you want one of the two options I can execute myself just say
which.

Thanks.
Yves

**Comment by ghost** [comment]
The GitHub account used at the time of the relevant commit was subsequently deleted. For a reason separate to this repository it was recreated, so `{id}` for the deleted and recreated GitHub accounts are not the same, whereas {user_name} for the former and current accounts are the same.

`{id}+{user_name}@users.noreply.github.com`

Both AUTHORS and .mailmap appear to be indexed by search engines.

I inform that as removing both the github email `{id}+{user_name}@users.noreply.github.com` entirely from the repositories' files and my name from `perl5340delta` can be arranged I would choose that option.

> fundamental problem

Leaving my name and email in AUTHORS would be acceptable, in the context of the foregoing.

**Comment by fluesvamp** [comment]
The following is posted if other Committers/Mere mortals have privacy concerns.

The content of checkAUTHORS doesn't appear to be indexed by search engines.

Based on this I presume that top-level repository files are indexed by search engines.

Perhaps the current AUTHORS and .mailmap  location is not the best owing to privacy concerns.

**Comment by demerphq** [comment]
On Fri, 5 Aug 2022 at 01:25, fluesvamp ***@***.***> wrote:

> The following is posted if other Committers/Mere mortals have privacy
> concerns.
>
> The content of checkAUTHORS doesn't appear to be indexed by search engines.
>
> Based on this I presume that top-level repository files are indexed by
> search engines.
>
> Perhaps the current AUTHORS and .mailmap location is not the best owing to
> privacy concerns.
>
The repo is public. The change log history is public. The email list is
public. All of them are indexed by search engines.  AUTHORS is and has been
part of the distribution forever and being in it is a point of pride for
many more developers than those who wish to be excluded. The fact is that
if someone is email harvesting then they are going to find these email
addresses.  I get it that some folks get twitchy when they do a search and
find their email in various places, but that is life contributing to a
public open source project. Its meant to be open. Privacy about who changed
what is the antithesis of open.

.mailmap is a file defined by the git project, we cant do email name
mapping and hiding without it. git and github use it. We use it because
they do.  If you have concerns about that, then I think you need to take
them to the git project. (I might raise it myself.) I think it is a
reasonable thing to say "I want a way to have an encrypted or hashed
version of the logic that .mailmap provides" and then maybe in a few years
that will filter out to the infra we use. But its really not very
reasonable to say 'use a different file', as that would defeat the purpose
of having it at all. Having said that we are putting all contributors in
the .mailmap file even if they arent being being used for blocking because
it makes the coding easier in many ways, however I can probably remove most
need for it. But ultimately if we remove you from the .mailmap file you
will APPEAR in github. We can't hide you in github without populating the
mailmap file, which itself will then be visible in github.

AUTHORS we have some control over, and we can remove people from it should
they request to be removed, and doing so will also remove them from github
views of the change logs and whatnot as well. But to do that currently we
update the .mailmap file.

Anyway, I have heard this thread and for historical I am well placed to
address some of the concerns raised here and ill do my best. But the
reality is that some of this is imposed by the infra and tooling we us and
until they change we are stuck.

cheers,
Yves





-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
Just wanted to post an update that I am working on this as time permits, my changes are nearly done, and a PR will be forthcoming this week.

**Comment by demerphq** [comment]
Hi all, I have pushed https://github.com/Perl/perl5/pull/20070 to remove this users details, and restructure and unify our AUTHORS related logic into one place (updateAUTHORS.pl) and add the ability to exclude people in a somewhat PII friendly way (hashed details). I expect to make some further patches to updateAUTHORS.pm once it gets merged or as part of the review process depending on my time availability.

**Comment by karenetheridge** [comment]
I would fulfill this user's request by adding a .mailmap entry for the user's name+email to "Anonymous" (or whatever other placeholder is deemed suitable).  That will prevent the name from being published in perl releases (release announcements, other pod files etc).

Removing the name from the repository entirely is not possible because we do not change the history of git commits - once a commit is made it is permanent.

**Comment by demerphq** [comment]
This is resolved now. Thank you for your patience while we got it merged.

**Comment by demerphq** [comment]
On Sat, 30 Jul 2022 at 02:01, apparluk ***@***.***> wrote:

> IIRC the following line in win32/{GNUmakefile,Makefile} was added via
> patches I submitted.
>
> # VS 2017 (VC++ 14.1) requires at minimum Windows 7 SP1 (with latest
> Windows Updates)
>
> That was prior to development transitioning to GitHub, and I don't think
> there's any code I wrote in the repo since that transition.
>

I find a reference to you in our commits.

https://github.com/Perl/perl5/commit/b998bd1a4a2c4e35a119ea73c7650a26e0060950

Where you yourself added your name and data to AUTHORS.

We later added the github email automatically as part of cleanup.

cheers,
Yves




-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
On Fri, 29 Jul 2022 at 22:10, Leon Timmermans ***@***.***>
wrote:

> Perhaps a Contributor would oblige and remove these lines, which would not
> result in a git history associated with this username.
>
> Like I said before, .mailmap and AUTHORS are generated files, so there's
> no point to manually removing them: they'd be added back on regeneration.
>
> Porting/checkAUTHORS.pl is the source of the link between the two, I'm
> not sure we can remove that without things breaking. I suspect we need to
> block your email first if we don't want to break tests.
>
FWIW IMO checkAUTHORS needs to go anyway. It should be replaced by running
updateAUTHORS and seeing if any changes are made. The only reason I did do
it earlier is checkAUTHORS does more than just checkAUTHORS and I wanted
updateAUTHORS to bake a while before we did the next step.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
On Sat, 20 Aug 2022 at 20:23, Karen Etheridge ***@***.***> wrote:
>
> I would fulfill this user's request by adding a .mailmap entry for the user's name+email to "Anonymous" (or whatever other placeholder is deemed suitable). That will prevent the name from being published in perl releases (release announcements, other pod files etc).

They asked not to be listed in our files at all. They dont care if
their name shows up in the changelog. They know that email harvesters
are aware of git .mailmap files and index and collect them. Their
objective is to not have their email or name listed in the project
files at all, they know that rewriting the history is not a realistic
option.

cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"
