### ISSUE TITLE
t/re/subst.t: superfluous SKIP block?

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#20086]
In `t/re/subst.t` there is a `SKIP:` block beginning at line 1013 and ending at line 1078.  However, AFAICT there is no `skip` statement within this block defining the requirements for the block to be skipped.

(There *is* another `SKIP:` block within the one starting at 1013.  That one starts at 1062, has a properly defined `skip` statement from 1063 to 1065, and ends at line 1076.)

```
1013 SKIP: {
1014     my $a_acute = chr utf8::unicode_to_native(0xE1); # LATIN SMALL LETTER A WITH ACUTE
1015     my $egrave = chr utf8::unicode_to_native(0xE8);  # LATIN SMALL LETTER E WITH GRAVE
1016     my $u_umlaut = chr utf8::unicode_to_native(0xFC);  # LATIN SMALL LETTER U WITH DIAERESIS
1017     my $division = chr utf8::unicode_to_native(0xF7);  # DIVISION SIGN
1018 
1019     is("ab.c" =~ s/\b/!/agr, "!ab!.!c!", '\\b matches ASCII before string, mid, and end, /a');
1020     is("$a_acute$egrave.$u_umlaut" =~ s/\b/!/agr, "$a_acute$egrave.$u_umlaut", '\\b matches Lat     in1 before string, mid, and end, /a');
...
1058     fresh_perl_like( '$_=""; /\B{sb}/;  s///g', qr/^$/, {},
1059         '[perl #126319: Segmentation fault in Perl_sv_catpvn_flags with \b{sb}'
1060     );
1061 
1062 SKIP: {
1063     if (! locales_enabled('LC_ALL')) {
1064         skip "Can't test locale (maybe you are missing POSIX)", 6;
1065     }
1066 
1067     setlocale(&POSIX::LC_ALL, "C");
1068     use locale;
1069     is("a.b" =~ s/\b/!/gr, "!a!.!b!", '\\b matches ASCII before string, mid, and end, /l');
1070     is("$a_acute.$egrave" =~ s/\b/!/gr, "$a_acute.$egrave", '\\b matches Latin1 before string,      mid, and end, /l');
1071     is("\x{100}\x{101}.\x{102}" =~ s/\b/!/gr, "!\x{100}\x{101}!.!\x{102}!", '\\b matches above-     Latin1 before string, mid, and end, /l');
1072 
1073     is("..." =~ s/\B/!/gr, "!.!.!.!", '\\B matches ASCII before string, mid, and end, /l');
1074     is("$division$division$division" =~ s/\B/!/gr, "!$division!$division!$division!", '\\B matc     hes Latin1 before string, mid, and end, /l');
1075     is("\x{2028}\x{2028}\x{2028}" =~ s/\B/!/gr, "!\x{2028}!\x{2028}!\x{2028}!", '\\B matches ab     ove-Latin1 before string, mid, and end, /l');
1076 }
1077 
1078 }
```
It seems that the `SKIP:` block starting at 1013 is superfluous and should be removed.  It was added in c8519dc7.  @khwilliamson, can you take a look?

**Comment by bram-perl** [comment]
In commit c8519dc797997ef2e60f58f25157026584a20c1e there is a SKIP block and it contains a `skip` statement inside it (line 1038 in that commit).
So that particular commits looks sort of ok (but it isn't entirely ok, see below).

A later commit 0b75bbb6da6ea3c792268f5137f00186d7b05652 modified the code and added an extra SKIP block (and also didn't indent the tests in the extra SKIP block).

That later commit looks like the culprit..
It did appear to fix one issue tho:

the first commit:
```
skip "Can't test locale", 6 unless $@;
```
-> it skips the test when there was no error (which doen't make sense)

the later commit:
```
if ($@) { skip "Can't test locale (maybe you are missing POSIX)", 6; }
```
-> it skips the tests when there is an error (which does make sense)

So arguably the only thing that needed fixing in the first commit was to replace `unless $@` with `if $@`.

**Comment by jkeenan** [comment]
This was fixed in https://github.com/Perl/perl5/pull/20240; closing.
