### ISSUE TITLE
macOS 10.15 CI pipeline is deprecated

### ISSUE THREAD

**Issue by demerphq** [Perl/perl5#20167]
**Description**
CI is currently failing with 

**This is a scheduled macOS-10.15 brownout. The macOS-10.15 environment is deprecated and will be removed on August 30th, 2022 For more details, see https://github.com/actions/virtual-environments/issues/5583**

See the annotations here: https://github.com/Perl/perl5/actions/runs/2935153722

We need to upgrade out macOS pipeline. 

**Steps to Reproduce**
N/A

**Expected behavior**
N/A

**Perl configuration**
N/A

**Comment by jkeenan** [comment]
@Toddr, @atoomic, others familiar with our CI setup ... what steps do we need to take to this problem with the MacOS rigs?

**Comment by atoomic** [comment]
I would recommend to remove macOS from the CI. 
macOS CI provides low value and use a lot of GitHub resource for no value

**Comment by toddr** [comment]
> I would recommend to remove macOS from the CI. macOS CI provides low value and use a lot of GitHub resource for no value

+1 Github charges quite a bit extra for macOS CI runs compared to Linux.

**Comment by jkeenan** [comment]
> I would recommend to remove macOS from the CI. macOS CI provides low value and use a lot of GitHub resource for no value

We seem to be getting a steady trickle of issues and/or smoke-test failures for Alpine Linux.  Could that distro be added to our CI setup?

**Comment by Leont** [comment]
>  macOS CI provides low value and use a lot of GitHub resource for no value

Does it? Knowing early if we break MacOS sounds important to me. What's the alternative?

**Comment by bram-perl** [comment]
> > I would recommend to remove macOS from the CI. macOS CI provides low value and use a lot of GitHub resource for no value
> 
> +1 Github charges quite a bit extra for macOS CI runs compared to Linux.

In what way does GitHub charge for it?
As far as I can tell the runners are free-of-charge for public projects..
(Or is that not the case for the perl5 project?)

**Comment by toddr** [comment]
> > > I would recommend to remove macOS from the CI. macOS CI provides low value and use a lot of GitHub resource for no value
> > 
> > 
> > +1 Github charges quite a bit extra for macOS CI runs compared to Linux.
> 
> In what way does GitHub charge for it? As far as I can tell the runners are free-of-charge for public projects.. (Or is that not the case for the perl5 project?)

Even for public projects, there are hidden limits to how many resources you can use. Because we smoke so much per commit, we're one of the few projects that push this limit. We've been given leniency, but during that discussion, it was made more clear that non-Linux platforms cost more to maintain because of how they were set up. I was told they have to have individual macs sitting in an awkward rack to do this work, so runs on this platform and windows for similar reasons were more costly. 

I expect there would be a limit where they'd tell us we need to have another conversation. This is why we've taken steps like doing a single ubuntu run and fail fast if that run does not succeed before we do the other platform runs.
