### ISSUE TITLE
^D doesn't always work in the perl debugger

### ISSUE THREAD

**Issue by x-yuri** [Perl/perl5#20307]
Module: lib/perl5db.pl

**Description**

<kbd>^D</kbd> doesn't work at the beginning of the session, after `n`, `s`, and maybe in some other cases.

From what I can see that happens because generally `$DB::single` is [reset](https://github.com/Perl/perl5/blob/v5.37.3/lib/perl5db.pl#L3106-L3107) before processing a command. But at the beginning of a session it doesn't get to that line. After `n` and `s` `DB::DB()` is supposedly set to be executed [again](https://github.com/Perl/perl5/blob/v5.37.3/lib/perl5db.pl#L3865-L3901) (`$DB::single = 1/2`).

**Steps to Reproduce**

`perl -de 'print 1; print 2'`, <kbd>^D</kbd>

**Expected behavior**

It runs the script to the end.

**Actual behavior**
It stops on the `print 2` statement.

**Perl configuration**

```
# perl -V output goes here
Summary of my perl5 (revision 5 version 36 subversion 0) configuration:
... (I will provide the rest if need be)
```

**Comment by tonycoz** [comment]
I suspect 80c1f1e45e8 changed the behaviour of this, with blead:
```
tony@venus:.../git/perl5$ ./perl -Ilib -lde 'print 1; print 2; '

Loading DB routines from perl5db.pl version 1.76
Editor support available.

Enter h or 'h h' for help, or 'man perldebug' for more help.

main::(-e:1):   print 1; print 2; 
  DB<1> 1
main::(-e:1):   print 1; print 2; 
  DB<1> 2
tony@venus:.../git/perl5$
```
I hit ^D only once, and since the eof flag is now left on, the second attempt to read also return eof and the run proceeds.

You said you expected the script to run to the end, but the documentation indicates both `q` and `^D` should *exit* the debugger, and q immediately exits without running the rest of the script.

**Comment by x-yuri** [comment]
> You said you expected the script to run to the end, but the documentation indicates both q and ^D should exit the debugger, and q immediately exits without running the rest of the script.

Oh, I meant it should stop, one way or another. Immediate exit sounds fine to me.

> I hit ^D only once, and since the eof flag is now left on, the second attempt to read also return eof and the run proceeds.

Can you elaborate on the eof flag? Where it's set/reset?

I'm not sure I understand your description, but for me `^D` at the beginning, and after `n`/`s` acts as if it's `n`. After you give it some other command, `^D` makes it exit.

Well, my first guess was that [here][a] the `$cmd eq '' && exit 0;` line disappears. AFAICT in this commit the debugger is replaced with the version from the [earlier commit][b]. Which doesn't have this line. But `Enter` and `^D` are no different in this respect. And the fact that it starts working after other commands contradicts with my guess.

[a]: https://github.com/Perl/perl5/commit/c07a80fdfe3926b5eb0585b674aa5d1f57b32ade#diff-bd5fd0912b1e542fce04510ad8cce82c181a0710f66ff5240aa4258b567b37b9L1409
[b]: https://github.com/Perl/perl5/commit/d338d6fe1dfdfdbc07c2d6d7a2a4ae7db5887d93

**Comment by tonycoz** [comment]
Any input stream has two flags, one to indicate that a read has reached end of file (^D on a console flags that) and a generic error flag.  There was a bug fixed by https://github.com/Perl/perl5/commit/80c1f1e45e8ef8c27d170fae7ade41971fe20218 that cleared both those flags in readline calls, and so the debugger didn't see the end of file.

I have a fix for this, but haven't been able to work up a test for it.
