### ISSUE TITLE
It is recommended to provide the official version of the binary pre-compiled file or installation package.

### ISSUE THREAD

**Issue by fenginsc** [Perl/perl5#20375]
I think the official compiled binaries should be made available for download and installed and ready to use.
Direct support for windows, macOS, linux with installers or pre-compiled binaries, just like other languages do.
Currently the third-party version is not the latest version 5.36, and their own compilation will fail for inexperienced people, so the user experience is very bad, I hope the official can pay attention to it.
thanks.

**Comment by jkeenan** [comment]
> I think the official compiled binaries should be made available for download and installed and ready to use. Direct support for windows, macOS, linux with installers or pre-compiled binaries, just like other languages do. thanks.

I believe that you have some misunderstandings of the roles which creators, maintainers and distributors of open source software play.  Open source software such as Perl or Python needs to be compiled for a particular machine in order to be run.  The number of different machines on which such software runs is so great that it would be impossible for anyone to create pre-compiled binaries for all potential users.  Perl, for example, needs, at the very least, to be compiled for particular hardware, a particular operating system (and a particular version of that operating system) and a particular C-compiler (and version thereof).

How exactly to configure Perl for a given machine is a decision best left to manufacturers and packagers.  Let's take Linux for an example.  There is no one "Linux" computer and no one "manufacturer" of "Linux" computers.  There is a Linux kernel which can be installed on different hardware.  There are dozens of different Linux distributions which provide "userland" programs which you see on your desktop or at your command line.  Debian, Ubuntu, RedHat, Gentoo ... the list goes on -- and the people behind each of these distributions make different choices as to what programs to (i) which programs are in "the base", i.e., get installed with the operating system; and (ii) which programs are made available in packages which an end-user such as yourself can install.  A distributor some of whose "base" programs are written in Perl will generally provide a pre-compiled binary to serve as the "system perl" or the "vendor perl", but this does not prevent you from, say, installing pre-compiled binaries from other sources or from configuring and compiling your own perl executable.

If you need further guidance on selecting a version of Perl that best fits your needs, I suggest you go to a more general Perl help site such as www.perlmonks.org or go to a mailing list or IRC channel with 'perl-help' in its name.

Thank you very much.
Jim Keenan
