### ISSUE TITLE
Segfault in Autoload found with afl

### ISSUE THREAD

**Issue by sigdevel** [Perl/perl5#20583]
Module: ```Autoload```

**Description:**

Tested ad Linux ```stapel.red-soft.ru 3.10.0-862.9.1.el7.x86_64```, but also reproduced this bug on other platforms x86_64 (for example, debian-based system).

**Steps to Reproduce:**

Just insert this string and run with ```perl -e``` for repeat or create file with line and run after: 
```perl
{my()=0;if(0){}p();{};AUTOLOAD{for(0=~/()/){if(//){bless{}}}}}
```
Gcc version: ```8.2.1 20180905 (Red Hat 8.2.1-3)```
Platform: ```Linux stapel.red-soft.ru 3.10.0-862.9.1.el7.x86_64 ```

**Expected behavior**

```bash
Core was generated by `./perl5.36.0 -e {my()=0;if(0){}p();{};AUTOLOAD{for(0=~/()/){if(//){bless{}}}}}'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f3e8cecb71e in _int_malloc () from /lib64/libc.so.6
```
Also attaching a link to the dump: https://github.com/a-shvedov/res/blob/master/fuzzing/perl/core.1050977.7z
#### **Perl configuration**

Reproduce on: ```5.36.0```

Building with flags:
```
    ldflags ='-Wl,-z,relro  -fstack-protector-strong -L/usr/local/lib'
    lddlflags='-lpthread -shared -Wl,-z,relro  -L/usr/local/lib -fstack-protector-strong'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong' 
```

**Comment by jkeenan** [comment]
I believe this can be further reduced to:
```
perl -we 'p();AUTOLOAD{for(0=~/()/){if(//){bless{}}}}'
```

**Comment by tonycoz** [comment]
This is infinite recursion.

The call to p() calls AUTOLOAD, which creates an object the `bless{}` (which is blessed into `main`, the root namespace), and then immediately releases it, so Perl tries to destroy it.

Since there's AUTOLOAD but no DESTROY, it tries to call AUTOLOAD to destroy the object... which then creates a new object and tries to destroy that, recursing.

Adding a DESTROY definition prevents the recursion:
```
$ ./perl -e '{my()=0;if(0){}p();{};AUTOLOAD{for(0=~/()/){if(//){bless{}}}}}'
Segmentation fault
$ ./perl -e '{my()=0;if(0){}p();{};AUTOLOAD{for(0=~/()/){if(//){bless{}}}}} sub DESTROY {}'
$
```
If you run with warnings:
```
$ ./perl -We '{my()=0;if(0){}p();{};AUTOLOAD{for(0=~/()/){if(//){bless{}}}}}'
Useless use of anonymous hash ({}) in void context at -e line 1.
Deep recursion on subroutine "main::AUTOLOAD" at -e line 1.
Segmentation fault
```
So this isn't something we treat as a bug.

The simpler:
```
$ ./perl -we 'p();AUTOLOAD{bless{}}'
Segmentation fault
```
also does unbounded recursion, and doesn't warn, and that may be a bug here.

**Comment by sigdevel** [comment]
Thanks for the clarification, then I think the issue may can be close.
