### ISSUE TITLE
[doc] sort docs say the compare function must return an integer, but it doesn't

### ISSUE THREAD

**Issue by petdance** [Perl/perl5#20691]
**Where**

perldoc -f sort

**Description**

`perldoc -f sort` says

> If SUBNAME is specified, it gives the name of a subroutine that returns an integer less than, equal to, or greater than 0, depending on how the elements of the list are to be ordered.

As far as I can tell, it only needs to be a numeric value, and does not need to be an integer.

I'll be glad to submit a PR if that's easiest.

----

Demo to show to myself that random non-integers work just fine.

```
use List::Util qw( shuffle );

my @x = shuffle 1..500;
say join( ', ', @x );
@x = sort floatcompare @x;
say join( ', ', @x );

sub floatcompare {
    if ( $a < $b ) {
        return -rand(1000) * 0.01;
    }
    elsif ( $a > $b ) {
        return rand(1000) * 0.01;
    }
    return 0;
}
```

**Comment by demerphq** [comment]
I think you are correct. The sort code guards its comparison state with this:

```
#define SORT_NORMAL_RETURN_VALUE(val)  (((val) > 0) ? 1 : ((val) ? -1 : 0))
```

FWICT if the return value is SvIOK true then it will be used, otherwise, it is treated as a float. Either way the result is passed through the above expression.

At least, this is what sort does with the return from overloaded comparison operators. The built ins a bit harder to follow, but i assume we have tested for consistency between overload and non-overloaded cases.

**Comment by petdance** [comment]
So shall I make a PR?

**Comment by demerphq** [comment]
Patch applied. Closing. Thanks @petdance. Sorry I didn't see your question sooner.
