### ISSUE TITLE
perlvar and perlre incorrectly state that /p regex modifier is a noop

### ISSUE THREAD

**Issue by haarg** [Perl/perl5#20728]
perlvar states:

> In Perl v5.18 and earlier, it is only guaranteed to return a defined value when the pattern was compiled or executed with the `/p` modifier. In Perl v5.20, the `/p` modifier does nothing, so `${^MATCH}` does the same thing as `$MATCH`.

> In Perl v5.18 and earlier, it is only guaranteed to return a defined value when the pattern was compiled or executed with the `/p` modifier. In Perl v5.20, the `/p` modifier does nothing, so `${^PREMATCH}` does the same thing as `$PREMATCH`.

> In Perl v5.18 and earlier, it is only guaranteed to return a defined value when the pattern was compiled or executed with the `/p` modifier. In Perl v5.20, the `/p` modifier does nothing, so `${^POSTMATCH}` does the same thing as `$POSTMATCH`.

perlre states:

> As another workaround for this problem, Perl 5.10.0 introduced `${^PREMATCH}`, `${^MATCH}` and `${^POSTMATCH}`, which are equivalent to `` $` ``, `$&` and `$'`, except that they are only guaranteed to be defined after a successful match that was executed with the `/p` (preserve) modifier. The use of these variables incurs no global performance penalty, unlike their punctuation character equivalents, however at the trade-off that you have to tell perl when you want to use them. As of Perl 5.20, these three variables are equivalent to `` $` ``, `$&` and `$'`, and `/p` is ignored. 

These are incorrect. The `/p` flag is not a no-op, and it is requires for the `${^PREMATCH}`, `${^MATCH}`, and `${^POSTMATCH}` variables to be populated.

**Comment by demerphq** [comment]
Ill review the code and fix. Thanks for the reminder.

**Comment by haarg** [comment]
This got tagged as documentation, but we should probably fix the behavior to match the docs (and fix the version numbers in the docs).

**Comment by demerphq** [comment]
On Fri, 20 Jan 2023 at 17:21, Graham Knop ***@***.***> wrote:

> This got tagged as documentation, but we should probably fix the behavior
> to match the docs (and fix the version numbers in the docs).
>

I will follow up on this tomorrow. I am not sure we can fix the behavior. I
have a vague memory that we thought that COW would replace the need for the
/p flag, but that it didnt work out as well as we had hoped. COW has a
refcount limit of 254 or something like that, and I think that in certain
cases we make potentially thousands of COW copies, so it ends up being
quadratic/254 or something like that.

yves

**Comment by haarg** [comment]
The `` $` ``, `$&`, and `$'` variables already are COW strings based on the matches. Fixing the behavior to match the docs would just mean making the `${^PREMATCH}`, `${^MATCH}`, and `${^POSTMATCH}` aliases for `` $` ``, `$&`, and `$'`, and disabling the effect of `/p`.

**Comment by demerphq** [comment]
Like I said, until I review it more carefully and check the history I am not ok with just changing the code and much more likely to change the docs. I have a recollection that I had to revert the last patch on this because COW is an insufficient solution for regex match copying. 

My recollection is that n a `while (/.../g)` against a long string we COW every iteration, and match time went quadratic, which is obviously not acceptable.

**Comment by demerphq** [comment]
I've spent the last few hours digging into the various COW bugs, and I am not nearly close to finishing. I suspect that the thing we should do is both change the docs and change the code.

First, COW only handles refcounts of 254, I have seen people say "so what", but `(N/254)**2` is still `O(N**2)`.

Second, COW doesn't handle various "irregular" foms of string. Eg, those with SvLEN == 0, or those with readonly flag, or those coming from XS where strings have been "perfectly allocated" so that SvCUR==SvLEN-1. (one extra byte for the null).

Third, COW interferes with other optimizations and breaks a number of them. 

I am still working out what to do about this in my head, and I still have more research to do, but I am definitely NOT ok, with changing the code in the short term. If we want to do anything about this in the short term we should change the docs to be more truthful to what happens now until we figure out what we will do about this in the future. 

I still thinking telling the regex engine "yes i want full preservation of the string" is a better approach than relying on COW to make `$&` "safe". COW does not make `$&` safe. It makes it safer but does not solve the problem 100%.
