### ISSUE TITLE
Compiler prototype error for C sub generated by ExtUtils::CBuilder::Base::have_compiler

### ISSUE THREAD

**Issue by djerius** [Perl/perl5#21109]
Module: ExtUtils::CBuilder::Base

**Description**
The declaration of the C function generated by `ExtUtils::CBuilder::Base::have_compiler` results  in a compile error on a Solaris CPAN tester running Perl 5.37.11:

http://www.cpantesters.org/cpan/report/6fe17dd2-f678-11ed-81f7-04d87368ee36

```
   1319 compilet-vLMAF.c:1:5: warning: function declaration isn&#39;t a prototype [-Wstrict-prototypes]
   1320  int boot_compilet() { return 1; }
   1321      ^~~~~~~~~~~~~
   1322 
   1323 # Failed test &#39;xs&#39;
   1324 # at t/alien.t line 83.
   1325 #   XSLoader failed
   1326 #  
```

That code is generated in `$VERSION = '0.280238'` of `ExtUtils::CBuilder::Base`

    207   else {
    208     print $FH "int boot_compilet() { return 1; }\n";
    209   }

**Comment by Leont** [comment]
Yeah that could use a `void`, C can be annoying like that

**Comment by tonycoz** [comment]
While we should fix that, it isn't an error.

The reason for the distribution failure seems more likely to be:
```
XSLoader failed
#     Can't load '/export/home/njh/.cpan/build/Alien-XPA-v2.1.20.7-1/_alien/tmp/test-alien-RTqVIj/auto/Test/Alien/XS/Mod0AAAA/Mod0AAAA.so' for module Test::Alien::XS::Mod0AAAA: ld.so.1: perl5.37.11: fatal: relocation error: file /export/home/njh/.cpan/build/Alien-XPA-v2.1.20.7-1/_alien/tmp/test-alien-RTqVIj/auto/Test/Alien/XS/Mod0AAAA/Mod0AAAA.so: symbol XPAAccess: referenced symbol not found at /export/home/njh/perl5/perlbrew/perls/perl-5.37.11-64all/lib/5.37.11/i86pc-solaris-64/DynaLoader.pm line 206.
#  at /export/home/njh/.cpan/build/Alien-Build-2.80-1/blib/lib/Test/Alien.pm line 483.
```

I suspect it's failing to find the name because the library is being built as a 32-bit library (based on `# #define SIZEOF_LONG 4` in confdefs.h, but perl is 64-bit.

The similar test with a 32-bit build of perl at http://www.cpantesters.org/cpan/report/4117372a-f674-11ed-bf24-09be7368ee36 passes since the perl and library match.

The other successful tests appear to having matching perl and library bitness, usually a 64-bit perl and a 64-bit library (based on SIZEOF_LONG)

gcc on Nigel's machine appears to default to 32-bit builds, and a 64-bit build of perl has been requested with -Duse64bitall for the 64-bit perl build.  gcc on my OpenIndiana VM defaults to a 64-bit build.

**Comment by djerius** [comment]
> While we should fix that, it isn't an error.

Apologies, I should have noticed it was a warning, not an error.  Sorry about that.

Thanks for the subsequent debugging.

**Comment by djerius** [comment]
Thanks!
