### ISSUE TITLE
Pod::Simple 3.45 breaks Pod::Html test suite

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#21311]
Module: Pod::Html

**Description**

As a result, the attempt to bring the latest Pod::Simple into blead was reverted: 643dfa470afd0bc8cec06c90184bc5c131035fa4.

I tracked down the break to changing this line in  XHTML.pm from
` s/&[^;]+;//g;            # Strip entities.`

to 
`s/[<>&'"]//g;            # Strip HTML special characters`

 from Pod::Simple  commit b074ee34e12279aeba3f5a3edc9968a6127c3de0

>  *Author: Graham Knop <haarg@haarg.org>
> Date:   Tue May 24 14:59:08 2022 +0200
> refactor link handling to encode in correct locations

@haarg is of the opinion that the bug is actually in Pod::Html:

> definitely seems to be a Pod::Html bug. it's trying to use the idify function, but isn't calling it properly. it's also relying on very specific internals. and the behavior the test wants is different from the documented behavior of htmlify.
i'd say that the logic from Pod::Simple::XHTML should just be copied into Pod::Html and modified to be what it desires.
or possibly change the test to expect quotes to be stripped

**Steps to Reproduce**

Revert 643dfa470afd0bc8cec06c90184bc5c131035fa4; run test suite
**Expected behavior**

No errors

**Perl configuration**

```
# perl -V output goes here
```
``

**Comment by haarg** [comment]
Previously, the idify was called internally with both HTML encoded and plain text content. It would try to cope with that, but this caused a number of issues, especially if you tried to override the idify function in a subclass, which it explicitly expects you to be able to do. My changes made it always operate in plain text, not encoded text.

Older versions of the code would convert a double quote (and any other "special" character) to a dash, but `&quot;` would be stripped entirely. Because Pod::Simple::XHTML would always pass the encoded form, double quotes would always get stripped. To maintain the same output, the new code strips all double quotes or other special html characters, rather than converting them to dashes.

The Pod-Html test suite is passing content to idify (via htmlify via anchorify) that includes
a double quote. It expects it to be converted to a dash, which it will then convert to an underscore. Since this isn't a form Pod::Simple::XHTML would have passed that content, maintaining the exact same output wasn't considered necessary.

The specifics of what was stripped vs what was converted was never documented.

I can see two solutions. First is that Pod-Html can just add its own logic for making anchors, with whatever behavior it prefers. It already is trying to generate links in a different form than Pod::Simple::XHTML, so I think this makes sense to do.

An alternative is to change Pod::Simple::XHTML's idify function to not strip double quotes, but instead convert them to dashes. I feel like the original behavior of stripping all double quotes and similar characters rather than converting them to dashes was bad, and only in place as a "safety" measure to remove HTML from its output. Since it no longer operates on HTML, this kind of aggressive stripping is no longer needed. But this would change its output in some cases, and break some of its own test cases.

**Comment by jkeenan** [comment]
For the record, this is the test failure observed in `ext/Pod-Html/t/anchorify.t ` when you run the test suite after saying `perl Porting/sync-with-cpan Pod::Simple` (attempting to sync in Pod-Simple-3.45).
```
$ cd t;TEST_JOBS=1 ./perl harness -v ../ext/Pod-Html/t/anchorify.t; cd -
../ext/Pod-Html/t/anchorify.t .. 
#   Failed test 'Got expected POD heads'
#   at t/anchorify.t line 39.
#     Structures begin differing at:
#          $got->{Has_Quotes} = Does not exist
#     $expected->{Has_Quotes} = '1'

not ok 1 - Got expected POD heads
ok 2 - anchorify() returned expected value
ok 3 - relativize_url() returned expected value
1..3
# Looks like you failed 1 test of 3.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 

Test Summary Report
-------------------
../ext/Pod-Html/t/anchorify.t (Wstat: 256 (exited 1) Tests: 3 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=3,  0 wallclock secs ( 0.00 usr  0.00 sys +  0.03 cusr  0.00 csys =  0.03 CPU)
Result: FAIL
```

**Comment by jkeenan** [comment]
If you add some Dumper code to that test's output ...
```
          {
            'Has_Hyphen_And_Space' => 1,
            'HasTrailingWordspace' => 1,
            'Subroutine' => 1,
            'HasLeadingWordspace' => 1,
            'Error' => 1,
            'DESCRIPTION' => 1,
            'NAME' => 1,
            'Has_Extra_InternalWordspace' => 1,
            'Has_QuestionMark' => 1,
            'HasQuotes' => 1,
            'Has_A_Wordspace' => 1,
            'Method' => 1
          },
          {
            'Has_Hyphen_And_Space' => 1,
            'Subroutine' => 1,
            'HasTrailingWordspace' => 1,
            'Has_Quotes' => 1,
            'HasLeadingWordspace' => 1,
            'DESCRIPTION' => 1,
            'Has_Extra_InternalWordspace' => 1,
            'NAME' => 1,
            'Has_QuestionMark' => 1,
            'Error' => 1,
            'Has_A_Wordspace' => 1,
            'Method' => 1
          }
```
... and squint, you'll see that the "got" has:
```
 'HasQuotes' => 1,
```
... whereas the "expected" has:
```
'Has_Quotes' => 1,
```
