### ISSUE TITLE
`Archive-Tar`: Core/CPAN Version Mismatch 

### ISSUE THREAD

**Issue by rwp0** [Perl/perl5#21402]
CPAN's [`Archive-Tar`](https://metacpan.org/dist/Archive-Tar) distribution is at version 3.02 while core [`Archive::Tar`](https://perldoc.perl.org/Archive::Tar) module is version 2.40.

[Version 3.02](https://metacpan.org/release/BINGOS/Archive-Tar-3.02) was released on _April 13, 2023_

[Version 2.40](https://metacpan.org/release/BINGOS/Archive-Tar-2.40) was released on _July 27, 2021_

This means it hasn't been updated for almost [2 years](https://www.timeanddate.com/date/durationresult.html?d1=13&m1=04&y1=2023&d2=27&m2=07&y2=2021).

The [RMG](https://metacpan.org/dist/perl/view/Porting/release_managers_guide.pod) instructs [Dual-Life](https://metacpan.org/dist/perl/view/Porting/release_managers_guide.pod#dual-life-CPAN-module-synchronisation) Core distributions to be synced with CPAN ones before releasing a new Perl version, either development or production.

Here's `core-cpan-diff -x -a` command (_run as per RMG_) output:

```
$ ./perl -Ilib Porting/core-cpan-diff -x -a

Archive::Tar:
    Perl: BINGOS/Archive-Tar-2.40.tar.gz
    CPAN: BINGOS/Archive-Tar-3.02.tar.gz
```

This was noticed by @leonerd while working on his [5.39.2 release](https://github.com/Perl/perl5/blob/b13b7a24d7ed748e05da63140d039ec1ed370441/Porting/release_schedule.pod#L43C36-L43C41).

---

CC @bingos (the distribution maintainer)

**Comment by iabyn** [comment]
On Sun, Aug 20, 2023 at 06:39:50AM -0700, Elvin Aslanov wrote:
> CPAN's [Archive-Tar](https://metacpan.org/dist/Archive-Tar) is at version 3.02 while core [Archive::Tar](https://perldoc.perl.org/Archive::Tar) is version 2.40.
> 
> [Version 3.02](https://metacpan.org/release/BINGOS/Archive-Tar-3.02) was released on April 13, 2023
> 
> [Version 2.40](https://metacpan.org/release/BINGOS/Archive-Tar-2.40) was released on July 27, 2021

There was an attempt to upgrade core to 3.02 in July 2023, but it was
quickly reverted because "t/90_symlink.t failed tests 6, 11, 16 and 20-21"

I don't know the details.

-- 
I took leave and went to hear Mrs Turner's daughter play on the harpsicon,
but Lord, it was enough to make any man sick to hear her; yet I was forced
to commend her highly.
    -- The Diary of Samuel Pepys, 1 May 1663

**Comment by leonerd** [comment]
It sounds nontrivial then. I'll leave as it stands for 5.39.2 and we can take a look at fixing it later hoping to have that in for .3

**Comment by jkeenan** [comment]
> CPAN's [Archive-Tar](https://metacpan.org/dist/Archive-Tar) is at version 3.02 while core [Archive::Tar](https://perldoc.perl.org/Archive::Tar) is version 2.40.
> 
> [Version 3.02](https://metacpan.org/release/BINGOS/Archive-Tar-3.02) was released on _April 13, 2023_
> 
> [Version 2.40](https://metacpan.org/release/BINGOS/Archive-Tar-2.40) was released on _July 27, 2021_
> 
> This means it hasn't been updated for almost [2 years](https://www.timeanddate.com/date/durationresult.html?d1=13&m1=04&y1=2023&d2=27&m2=07&y2=2021).
> 
> The [RMG](https://metacpan.org/dist/perl/view/Porting/release_managers_guide.pod) instructs [Dual-Life](https://metacpan.org/dist/perl/view/Porting/release_managers_guide.pod#dual-life-CPAN-module-synchronisation) Core distributions to be synced with CPAN ones before releasing a new Perl version, either development or production.
> 
> Here's `core-cpan-diff -x -a` command (_run as per RMG_) output:
> 
> ```
> $ ./perl -Ilib Porting/core-cpan-diff -x -a
> 
> Archive::Tar:
>     Perl: BINGOS/Archive-Tar-2.40.tar.gz
>     CPAN: BINGOS/Archive-Tar-3.02.tar.gz
> ```
> 
> This was noticed by @leonerd while working on his [5.39.2 release](https://github.com/Perl/perl5/blob/b13b7a24d7ed748e05da63140d039ec1ed370441/Porting/release_schedule.pod#L43C36-L43C41).
> 
> CC @bingos (the distribution maintainer)

These have been previously noted.  See: https://github.com/Perl/perl5/pull/21268#issuecomment-1643507502 and https://rt.cpan.org/Ticket/Display.html?id=149072.

I periodically run `Porting/core-cpan-diff` to identify dual-life distributions where the CPAN versions of distros are ahead of what we currently have in `cpan/`.  Archive-Tar has fallen into this category for some time.  However, we also need to look at the CPAN versions bug queues, their CPANtesters reports, etc., to see whether those newer CPAN versions are in good enough shape to be synched into core.  As the RT ticket above suggests, both @steve-m-hay and myself feel that Archive-Tar's latest version is currently not good enough to be brought into core.  So while I ran `Porting/sync-with-cpan` several times in recent days to bring CPAN distros into core, I refrained from doing so re Archive::Tar.  I'm hoping that @bingos can handle the test failure and do a new CPAN release.  He will then sync this into core; he's done more of this synching than anyone else!

**Comment by jkeenan** [comment]
> > CPAN's [Archive-Tar](https://metacpan.org/dist/Archive-Tar) is at version 3.02 while core [Archive::Tar](https://perldoc.perl.org/Archive::Tar) is version 2.40.
> > [Version 3.02](https://metacpan.org/release/BINGOS/Archive-Tar-3.02) was released on _April 13, 2023_
> > [Version 2.40](https://metacpan.org/release/BINGOS/Archive-Tar-2.40) was released on _July 27, 2021_
> > This means it hasn't been updated for almost [2 years](https://www.timeanddate.com/date/durationresult.html?d1=13&m1=04&y1=2023&d2=27&m2=07&y2=2021).
> > The [RMG](https://metacpan.org/dist/perl/view/Porting/release_managers_guide.pod) instructs [Dual-Life](https://metacpan.org/dist/perl/view/Porting/release_managers_guide.pod#dual-life-CPAN-module-synchronisation) Core distributions to be synced with CPAN ones before releasing a new Perl version, either development or production.
> > Here's `core-cpan-diff -x -a` command (_run as per RMG_) output:
> > ```
> > $ ./perl -Ilib Porting/core-cpan-diff -x -a
> > 
> > Archive::Tar:
> >     Perl: BINGOS/Archive-Tar-2.40.tar.gz
> >     CPAN: BINGOS/Archive-Tar-3.02.tar.gz
> > ```
> > 
> > 
> > This was noticed by @leonerd while working on his [5.39.2 release](https://github.com/Perl/perl5/blob/b13b7a24d7ed748e05da63140d039ec1ed370441/Porting/release_schedule.pod#L43C36-L43C41).
> > CC @bingos (the distribution maintainer)
> 
> These have been previously noted. See: [#21268 (comment)](https://github.com/Perl/perl5/pull/21268#issuecomment-1643507502) and https://rt.cpan.org/Ticket/Display.html?id=149072.
> 
> I periodically run `Porting/core-cpan-diff` to identify dual-life distributions where the CPAN versions of distros are ahead of what we currently have in `cpan/`. Archive-Tar has fallen into this category for some time. However, we also need to look at the CPAN versions bug queues, their CPANtesters reports, etc., to see whether those newer CPAN versions are in good enough shape to be synched into core. As the RT ticket above suggests, both @steve-m-hay and myself feel that Archive-Tar's latest version is currently not good enough to be brought into core. So while I ran `Porting/sync-with-cpan` several times in recent days to bring CPAN distros into core, I refrained from doing so re Archive::Tar. I'm hoping that @bingos can handle the test failure and do a new CPAN release. He will then sync this into core; he's done more of this synching than anyone else!

The Archive-Tar maintainers have not responded to the tickets filed in their bug-trackers.  So we're still not in a good position to synch Archive-Tar's latest CPAN release into core.  Since the biggest obstacle is a test failing on Windows, if there is anyone with access to Windows who could explore https://rt.cpan.org/Ticket/Display.html?id=149072, that would be very helpful.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
In addition, I just filed this GH issue: https://github.com/jib/archive-tar-new/issues/43

**Comment by sisyphus** [comment]
FWIW, I believe the below patch caters portably for those Windows systems where symlink() is available (and $Config{d_symlink} is defined), but where proper functionality has not been enabled.
In this situation, symlink() does not throw an error or warning (unless called with the wrong number of arguments), but simply does nothing in silence. 
That's how it is on my Windows 11 system, and presumably also on the Windows CI system.

Currently, $Config{d_symlink} being defined on a Windows system does <b>not</b> imply that symlink() is fit for purpose - which probably defies the expectations of many,
At most, on Windows it merely guarantees that symlink() will not warn or throw an error when called with 2 arguments.

Maybe the problem would be better addressed in perl itself.
Otherwise, I'm happy to present this patch upstream, to the appropriate place which, I gather is https://github.com/jib/archive-tar-new/issues/43, recently opened by @jkeenan .

Cheers,
Rob
```
--- t/90_symlink.t	2023-10-22 11:49:19.305592800 +1100
+++ t/91_symlink.t	2023-10-22 15:39:42.276802800 +1100
@@ -9,12 +9,34 @@
 use Config;
 
 ### developer tests mostly
-plan skip_all => "Skipping tests on this platform"
   if ($^O !~ /(linux|bsd|darwin|solaris|hpux|aix|
               sunos|dynixptx|haiku|irix|next|dec_osf|svr4|sco_sv|unicos|
-              cygwin)/x and !$Config{d_symlink});
+             cygwin)/x and !$Config{d_symlink}) {
+    plan skip_all => "Skipping tests on this platform";
+}
+elsif ($^O =~/MSWin32/i) {
+    # Having already processed the above if{} block, I'm not
+    # sure that we actually need to eval{} the symlink() call.
+    # But we'll eval{} it anyway ... just in case:
+
+    eval{symlink('README', 'README.symlink');};
+    # skip all if $@ is set.
+    plan skip_all => "Skipping tests on this platform" if $@;  
+}
 plan 'no_plan';
 
+my $winchange = 0;
+
+if($^O =~ /MSWin32/i && !(-e 'README.symlink')) {
+    # On some configurations of windows, the above symlink() will
+    # have failed to perform its intended task, yet not have thrown
+    # an  error. For such cases, we need to conditionally alter 
+    # 2 of the tests below.
+
+    $winchange = 1 unless -e 'README.symlink'; # alter 2 tests
+    unlink 'README.symlink';
+}
+
 my $Class   = 'Archive::Tar';
 my $Dir     = File::Spec->catdir( qw[src linktest] );
 my %Map     = (
@@ -50,9 +72,22 @@
 
             my $rv = eval { $tar->extract } || 0;
             ok( !$@,                "       No fatal error" );
+
+            if($winchange) {
+              my $expect = '';
             is( !!$rv, !!$expect,   "       RV as expected" );
-            like( $warning, $regex, "       Error matches $regex" );
+            }
+            else {
+              is( !!$rv, !!$expect,   "       RV as expected" );
+            }
 
+            if($winchange) {
+              my $regex = qr/No such file/;
+              like( $warning, $regex, "       Error matches $regex" );
+            }
+            else {
+              like( $warning, $regex, "       Error matches $regex" );
+            }
             rmtree( 'linktest' );
         }
     }
```

**Comment by jkeenan** [comment]
Today I provided additional analysis of this problem upstream at https://rt.cpan.org/Ticket/Display.html?id=149072#txn-2625092

**Comment by sisyphus** [comment]
I've logged into rt and tried updating the ticket twice, but all I get is a 403 forbidden.
FWIW, here's what I was trying to post:
```
I suggest that, for Windows, t/90_symbolic.t should "skip_all" unless the creation of symbolic links is enabled.
Something like the following patch:

##############################################
--- 90_symlink.t_orig   2023-03-31 00:52:55.000000000 +1100
+++ 90_symlink.t        2023-12-05 12:42:57.342716800 +1100
@@ -8,11 +8,34 @@
 use Test::More;
 use Config;

+my $win32_symlink_enabled = 0;
+
+if($^O =~ /MSWin32/i && $Config{d_symlink}) {
+  # Creation of symlinks is available to this system,
+  # but might not have been enabled. We check on this
+  # by checking whether symlink() actually works.
+
+  if(-e '../Makefile.PL') {
+    symlink '../Makefile.PL', 'make.sym';
+    if(-e 'make.sym') {
+      $win32_symlink_enabled = 1;
+      unlink 'make.sym';
+    }
+  }
+  else {
+    warn "Cannot establish whether symlink() is enabled as Makefile.PL was not found";
+    $win32_symlink_enabled = 1; # We have no reason to assume otherwise.
+  }
+}
+
 ### developer tests mostly
-plan skip_all => "Skipping tests on this platform"
-  if ($^O !~ /(linux|bsd|darwin|solaris|hpux|aix|
+if (($^O !~ /(linux|bsd|darwin|solaris|hpux|aix|
               sunos|dynixptx|haiku|irix|next|dec_osf|svr4|sco_sv|unicos|
-              cygwin)/x and !$Config{d_symlink});
+            cygwin)/x and !$Config{d_symlink})
+            ||
+            ($^O =~ /MSWin/i and !$win32_symlink_enabled)) {
+  plan skip_all => "Skipping tests on this platform";
+}
 plan 'no_plan';

 my $Class   = 'Archive::Tar';

##############################################

That avoids the failures on my Windows 11 machine, where I see those test failures.
(I've allowed for the possibility that "../Makefile.PL" might not be found, though I'm not so sure that's really necessary.)

We could finesse it so that only the failing tests are skipped ... I don't know if that would really achieve anything.
```
UPDATE: Replaced an instance of <code>'Makefile.PL'</code> with <code>'../Makefile.PL'</code>) 

I might have already suggested something similar in a related github issue or cpan ticket ... not sure.

**Comment by jkeenan** [comment]
> I've logged into rt and tried updating the ticket twice, but all I get is a 403 forbidden. FWIW, here's what I was trying to post:

Hmm, yeah, I got that same problem yesterday when I tried to update that ticket through the web interface.  Had to resort to sending mail. 

>
> 
> I suggest that, for Windows, t/90_symbolic.t should "skip_all" 
unless the creation of symbolic links is enabled.
> [snip]
> 

What I think we should do right now for the Perl core distribution is to exclude `t/90_symlink.t` from being brought into core altogether.  This would require us to (a) modify the Archive::Tar entry in `Porting/Maintainers.pl`; (b) synch in CPAN version 3.02; (c) increment `$VERSION`, presumably to `3.02_001`, so as to indicate that P5P has patched what we're shipping with core.  (I can take care of these steps assuming we go forward in this direction.)

My rationale for this approach is:
* From 2008 up through CPAN release 2.40, the maintainers of Archive-Tar had a comment in `t/90_symlink.t` which indicated that the unit tests therein were for "developers" and that the tests would be skipped entirely unless the person running the tests provided `@ARGV` on the command-line.
* As a consequence, during that entire period all the tests in `t/90_symlink.t` were skipped on *all* operating systems, not just on Windows and similarly symlink-less systems.  *And yet we survived!*
* The `skip_all` condition in Archive-Tar-3.02 is hacky and our attempts to correct it will make it even hackier.
* It should be up to the Archive-Tar maintainers to decide whether the unit tests within `t/90_symlink.t` run *in general* (*i.e.,* on all platforms in contexts such as CPANtesters) and on which platforms they should not be run.  If those tests really are only for people working on Archive-Tar itself, they should be moved out of `t/` so that automated testers (like Perl core) do not encounter them.
* Once the Archive-Tar maintainers make the necessary changes and release a new version to CPAN, then we can re-modify `Porting/Maintainers.pl` as needed and synch that new version into core.

I'll provide a pull request later today to that effect.

**Comment by jkeenan** [comment]
> 
> 
> I'll provide a pull request later today to that effect.

https://github.com/Perl/perl5/pull/21691

**Comment by sisyphus** [comment]
> What I think we should do right now for the Perl core distribution is to exclude t/90_symlink.t from being brought into core altogether.

I don't see why that is necessary.
AIUI, the current version of 90_symlink.t in A-T-3.02 can only do a "skip all" if $Config{d_symlink} is not defined - which, I would expect, is a fairly rare case.
And yet, cpantesters are reporting only 2 FAIL results for Archive-Tar-3.02. (I'm unable to get a look at what those fails are.)
I thought it was only Windows that was having trouble with 90_symlink.t.
Is the problem more widespread than I realize ?

**Comment by jkeenan** [comment]
> > What I think we should do right now for the Perl core distribution is to exclude t/90_symlink.t from being brought into core altogether.
> 
> I don't see why that is necessary. AIUI, the current version of 90_symlink.t in A-T-3.02 can only do a "skip all" if $Config{d_symlink} is not defined - which, I would expect, is a fairly rare case. 

As long as the upstream maintainers of Archive-Tar [characterize the tests](https://github.com/jib/archive-tar-new/blob/9ecd778981b76ee18574dfc052c13f8ec8cd2c56/t/90_symlink.t#L11C1-L11C1
) in `t/90_symlink.t` as:
```
### developer tests mostly
```
... then those tests should not be included in a directory (`t/`) where they will be picked up by automated testers such as the Perl 5 core distribution test suite.  To date the core's test suite has, AFAICT, *always* skipped all of the tests inside `t/90_symlink.t` on *all* platforms because of the way the `skip_all` condition inside that file (up through Archive-Tar-2.40) has been formulated.  It should be the responsibility of the upstream maintainers to clarify which unit tests are for general use (hence, included in a file under `t/`) and which are truly for Archive-Tar developers only (and hence, moved out from under `t/`).  @sisyphus, you and I have obviously spent *many* hours trying to figure out what's going on here, but it's not even clear that these tests should have been included in the Perl 5 test suite in the first place.  Until the upstream maintainers investigate this, I think the simplest thing for P5P to do is to exclude this file from the sync-with-cpan process.  That way we'll get the benefit of code improvements in Archive-Tar-3.00 and 3.02.

> And yet, cpantesters are reporting only 2 FAIL results for Archive-Tar-3.02. 

That's more a reflection of our lack of extensive CPANtesters rigs on Windows.

**Comment by sisyphus** [comment]
> \### developer tests mostly

Yes, I think that should be removed.
And I don't see that regex on $^O as serving any useful purpose.
AFAICT, the following  would serve just  as well:
```
plan skip_all => "Skipping tests on this platform"
      if !$Config{d_symlink}
```
Is there a purpose in running the tests on the systems specified in the regex when $Config{d_symlink} is undef ?
If there is, then I guess it should stay - it's apparently not causing any problems.

However, removing/disabling the 90_symlink tests for <b>all</b> systems seems like overkill to  me - given that the only problem is with those Windows systems that define $Config{d_symlink}, but have not enabled the symlink functionality.

Then again .... having experienced it in the past, I do understand the frustration of trying to get "cpan" core modules updated - and if @jkeenan's proposal is what's needed in order to get it fixed, then so be it.

**Comment by jkeenan** [comment]
Addressed by https://github.com/Perl/perl5/commit/54f925e1d05ec5ccff2d0d1c62e34c5c1d6a0897; closing.
