### ISSUE TITLE
[doc] List Perl 5.38 in release_schedule.pod

### ISSUE THREAD

**Issue by bschmalhofer** [Perl/perl5#21574]
**Where**
https://metacpan.org/dist/perl/view/Porting/release_schedule.pod

**Description**
Perl 5.38 is not mentioned in the list of stable releases. The only mention of Perl 5.38 is in the Perl 5.37 section, https://metacpan.org/dist/perl/view/Porting/release_schedule.pod#Perl-5.37.

**Comment by rwp0** [comment]
Unfortunately this cannot be changed until the 5.38.1 release, I think.

This seems to be fixed in the current [document](https://github.com/Perl/perl5/blob/cea3213ec54ab4c04bc7128d4c610f4c55e2d5e8/Porting/release_schedule.pod) hosted on GitHub:

https://github.com/Perl/perl5/blob/cea3213ec54ab4c04bc7128d4c610f4c55e2d5e8/Porting/release_schedule.pod#L14-L22

**Comment by jkeenan** [comment]
> Unfortunately this cannot be changed until the 5.38.1 release, I think.
> 
> This seems to be fixed in the current [document](https://github.com/Perl/perl5/blob/cea3213ec54ab4c04bc7128d4c610f4c55e2d5e8/Porting/release_schedule.pod) hosted on GitHub:
> 
> https://github.com/Perl/perl5/blob/cea3213ec54ab4c04bc7128d4c610f4c55e2d5e8/Porting/release_schedule.pod#L14-L22

Yes, that's correct.  it's been fixed in blead since July 3.  Hence it appears in each monthly dev release (October's is currently in progress, I believe) and will appear in any 5.38.* maintenance release and in perl-5.40 next May.  metacpan.org posted that page on July 2 and is free to update it if it chooses; Perl 5 Porters does not govern metacpan.  No action necessary on the part of P5P.

**Comment by bschmalhofer** [comment]
Thanks for the prompt response!
