### ISSUE TITLE
Doing more with __PACKAGE__

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21630]
Please allow me to urge that more could be done with __PACKAGE__ as illustrated below:

```
package AAA;

# Should produce sub AAA::BBB:CCC
 sub __PACKAGE__(BBB CCC) {1} # Illegal character in prototype for AAA::__PACKAGE__ : BBB CCC

# Should produce: AAA::BBB::CCC(1)
say STDERR __PACKAGE__(BBB CCC)(1);  # syntax error near "(BBB CCC)"
```

**Comment by rwp0** [comment]
I'm sorry, I don't understand why we may need to define the `__PACKAGE__` subroutine?

**Comment by Grinnz** [comment]
The first example is not feasible because subroutine calls are not allowed in the definition of subroutine names. The second one can be written quite simply: `__PACKAGE__."::BBB::CCC"`, which cannot be then used to call a subroutine under strict 'refs', but that would also be true if the string was formed as you describe.

**Comment by mauke** [comment]
Is this a bug report? A feature request? A comment?

I can't tell what this ticket is supposed to be about.

**Comment by leonerd** [comment]
It's unclear (or unfeasible) what is being requested here. There's been no comment in a while. I'm going to close the bug.
