### ISSUE TITLE
Can't return array to lvalue scalar context

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21631]
The use of lvalue **my sub**'s can make sigils somewhat optional as shown below for a scalar variable.  But further progress to a sigil optional language is stymied by the an inability to return arrays from lvalue subs in an analogous way.  May I urge that this restriction be removed as it causes unnecessary surprises?

```
my $a;  my sub a():lvalue {$a}

a = 'aaa'; say STDERR a.a.a;   # aaaaaaaaa

my @A;
my sub A():lvalue {@A}         # Can't return array to lvalue scalar context

A = ('aaa'); say STDERR A.A.A; # aaaaaaaaa
```

**Comment by Grinnz** [comment]
This is not an error in the sub definition but in your call. You have done a scalar assignment to the subroutine. You must use parentheses to do a list assignment to a subroutine, this is one of the instances where parentheses are semantically significant in Perl: `(A) = ('aaa');`

Additionally the output is subsequently `111` because `@A` is evaluated in scalar context by the concatenation operator.

**Comment by Leont** [comment]
Yeah, this is not a bug
