### ISSUE TITLE
Say "Perl: Out of memory", not just "Out of memory"

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#21672]
Please have perl print
> Perl: out of Memory

not just

> Out of memory.

Else it is hard to tell what printed that message.

https://github.com/szabgab/perlmaven.com/issues/583

Yes, I know perl doesn't like to say "Perl: " before its
messages. But it would be nice if it was like bash, and did.

**Comment by guest20** [comment]
The example at  https://perlm aven.com/out-o f-memory  shows a user knowingly running a perl script that consumes more memory than the system has. 

What, if not perl, would be in a position to print that error to their terminal?

**Comment by jidanni** [comment]
The main reason, why there is so much confusion as to what is printing that message, is that perl's messages always always always always always have some line number mentioned in them.

Yes, they might not say which item on a certain line caused the problem, but at least they have a line number and the name of some file attached to them.

So if perl would be kind enough to print that also, instead of just throwing up its hands and sayimg "out of memory" , then it would save a tons of confusion for all the people trying to hunt problems down.

That way people would not assume that this could not possibly be perl printing the message, so must be something else, so the only other thing would be the owner of the memory, which is the kernel.

**Comment by jidanni** [comment]
And Googling for "Perl out of memory"  shows many people not only not clear who is printing the message, but also desperately trying to find which part of their program is making the error. So adding a line number would help enormously. Certainly perl has some up its sleeves that it could print while printing the Out of memory message.

You might say that being  so chatty might make perl's look like python's messages. Well yes.

**Comment by jidanni** [comment]
I mean, even messages from the telephone company, have "message number 374-M" added  to them at least. That way when people call customer service they can refer to the message number.

That's why this particular message seems so unlike perls'. It seems sort of like some spam message injected trying to get people to click on something. 

Out of diis space. Click here to buy some more. Out of memory. Click here to buy some more. "Your system is not optimized." Etc. 

Yes, there is "no  click here to buy some more" attached this message, but still.. it looks very suspicious. Not like any other message perl has ever made.

I mean usually perl is not in such a panic that it can't remember at least one line number. 

Okay. In this case there may be good reasons for not knowing the line number, but at least it should know it's own name, perl, and print that too.

**Comment by guest20** [comment]
> even messages from the telephone company, have "message number 374-M"

The error number in this case is "out of memory", and you did quote that when you contacted customer service. 

> And Googling for "Perl out of memory"

1. nobody starts a stackoverflow/perlmonks thread with "look at this cool and totally explained error message - I don't have questions, i just think it's nifty".
That's not what forums are for. 

2. Most of them are not "is this from perl?", but "why does the perl I wrote fill up all of ram?", and the answers are:
- you did a combinatorial on accident
- you read more files than you thought
- you read bigger files than you thought
- you read a lot of small files, and kept them in memory after processing (maybe on accident)
- you slurped a whole binary file because you were trying to read it a line at a time, and it did not have lines
- you used a large number as the index of an array: `[]->[[]]++ # oops ` or in `x` or in `unpack`

3. Your search term _already_ says perl in it, so it's pretty clear you _already_ know it came from perl.

The actual question is "What? Why did the x operator consume all the memory?"

The answer is [in perlsecpolicy](https://perldoc.perl.org/perlsecpolicy#Out-of-memory-errors):
> Out of memory errors
> Common Perl constructs such as pack, the x operator, and regular expressions accept numeric quantifiers that control how much memory will be allocated to store intermediate values or results. If you allow an attacker to supply these quantifiers and consume all available memory, the Perl interpreter will not prevent it.

It sounds nice to say "give me a line number", but which line number? Every single variable in the program occupies memory. Files and sockets are buffered, regex captures come and go, and the interpreter even keeps some for itself, just as a little treat. 

If your program is any more complicated than ` "0~" x ~0 ` you're going to have a lot of different things using memory, and giving out the line number of the last thing to want memory is likely to point you at the `my $i` in some random for loop, or the `my ($self,@misc) = @_` in some sub call. 

One of the PM articles in this search result also mentions that the message is short because strings take up memory, and there might not be enough of that around to fit a longer error message into. (that might be less true on modern hardware though)

**Comment by jidanni** [comment]
It's just like "out of money."  I'm not concerned why I ran out of money, yet.  First I would just like to answer the question:  Who says I'm out of money? Was it my bank, my dentist, my credit union, my sports club, the IRS...?

Anyway I'm glad to see the 75 changes have been made due to my bug report. Thank you everybody.
