### ISSUE TITLE
[doc] (more "[build]", if that existed) darwin.sh has a typo that can't work as written

### ISSUE THREAD

**Issue by gsteemso** [Perl/perl5#21727]
In the file "perl-5.38.2/hints/darwin.sh" in the distribution tarball:

At lines 163-165, there is a conditional to make sure a command-line option I don't recognize gets assigned ' ' if it arrived with an empty value.  Unfortunately, the name tested for the conditional contains one fewer "c" than the name that gets adjusted.  Not being able to guess its purpose, I can't speculate as to which spelling might be correct.

I've no idea whether this really matters much -- it doesn't sound like anyone's triggered it in all its years of existence -- but it leapt out at me as "trouble waiting to happen" when I was hunting through the file for other, unrelated reasons.

**Comment by jkeenan** [comment]
> In the file "perl-5.38.2/hints/darwin.sh" in the distribution tarball:
> 
> At lines 163-165, there is a conditional to make sure a command-line option I don't recognize gets assigned ' ' if it arrived with an empty value. Unfortunately, the name tested for the conditional contains one fewer "c" than the name that gets adjusted. Not being able to guess its purpose, I can't speculate as to which spelling might be correct.
> 
> I've no idea whether this really matters much -- it doesn't sound like anyone's triggered it in all its years of existence -- but it leapt out at me as "trouble waiting to happen" when I was hunting through the file for other, unrelated reasons.

Thanks for reporting this.  However, it's probably intentional (though the intention is probably lost in the mists of time).  If you search the codebase with this command:
```
$ ack -i 'c?ccdlflags' .
```
... you will find *many* files, including other `hints/*.sh` files, that contain one of both of the strings `ccdlflags` and `cccdlflags`.

Can anyone on list elaborate?

**Comment by mauke** [comment]
The relevant section of the hints file:
```sh
case "$ccdlflags" in		# If passed in from command line, presume user knows best
'')
   cccdlflags=' '; # space, not empty, because otherwise we get -fpic
;;
esac
```
Looks very intentional to me. I read this as: If the user has cleared the "flags used for dynamic linking" variable, also clear the "flags used for compiling a dynamic library" variable. (`-fpic` tells the compiler to generate position-independent code; it is not a linker flag.)

See also `perldoc Config`:

> - `cccdlflags`
> 
>   From `dlsrc.U`:
> 
>   This variable contains any special flags that might need to be passed with `cc -c` to compile modules to be used to create a shared library that will be used for dynamic loading.  For hpux, this should be +z.  It is up to the makefile to use it.
> 
> - `ccdlflags`
> 
>   From `dlsrc.U`:
> 
>   This variable contains any special flags that might need to be passed to cc to link with a shared library for dynamic loading.  It is up to the makefile to use it.  For sunos 4.1, it should be empty.

**Comment by gsteemso** [comment]
You are correct. My mistake. Marking this closed.
