### ISSUE TITLE
Blead breaks build in g++, clang++ builds on some platforms

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#21948]
Compiling `perl` using `g++` or `clang++` has started to fail on certain platforms, such as several of the BSDs.

For example, building on FreeBSD-13 with the following configuration:
```
$ g++ --version | head -n1
g++ (FreeBSD Ports Collection) 12.2.0

$ sh ./Configure -des -Dusedevel -Dcc=g++ && make test_prep
```
... the build stops here:
```
g++ -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DNO_POSIX_2008_LOCALE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_FORTIFY_SOURCE=2 -O2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wwrite-strings -Wno-use-after-free locale.c
locale.c: In function 'void S_ints_to_tm(tm*, int, int, int, int, int, int, int, int, int)':
locale.c:8072:25: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 8072 |         mytm->tm_zone = zone;
      |                         ^~~~
      |                         |
      |                         const char*
*** Error code 1

Stop.
make: stopped in /usr/home/jkeenan/gitwork/perl
```
Line 8072 in `locale.c` was last modified in blead yesterday.
```
commit 36e41d53ff6a5995c16234f8027ef34b5e6a34cc
Author:     Karl Williamson <khw@cpan.org>
AuthorDate: Wed Jan 10 11:30:11 2024 -0700
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Wed Feb 7 10:59:05 2024 -0700

    Don't use both mini_mktime() and mkttime()
```
`g++` builds on Linux so far appear to be unaffected.

@khwilliamson, can you take a look?

**Comment by jkeenan** [comment]
On the same FreeBSD-13 machine as above, we get a similar build failure using `clang++` instead of `g++`:
```
$ clang++ --version
FreeBSD clang version 14.0.5 (https://github.com/llvm/llvm-project.git llvmorg-14.0.5-0-gc12386ae247c)
Target: x86_64-unknown-freebsd13.2
Thread model: posix
InstalledDir: /usr/bin

clang++ -c -DPERL_CORE -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -DNO_POSIX_2008_LOCALE -I/usr/local/include -O2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings locale.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
locale.c:8072:25: error: assigning to 'char *' from 'const char *' discards qualifiers
        mytm->tm_zone = zone;
                        ^~~~
1 error generated.
*** Error code 1

Stop.
```

**Comment by mauke** [comment]
OK, this is fun. We have this pair of assignments in `S_ints_to_tm`:
```c
#  ifdef HAS_TM_TM_ZONE
        const char *zone = mytm->tm_zone;  // #1
#  endif
        // ...
#  ifdef HAS_TM_TM_ZONE
        mytm->tm_zone = zone;  // #2
#  endif
```

On BSD systems, `tm_zone` is of type `char *`, so assignment #<span></span>2 strips away `const` from `zone`, which is declared as `const char *`. This is an error in C++. (It is actually an error in C, too, but C compilers commonly keep going anyway.) The code could be fixed by removing the `const` qualifier from the declaration in #<span></span>1.

However, on Linux, `tm_zone` is of type `const char *`, so #<span></span>2 is correct. However, removing `const` from #<span></span>1 would introduce the problem we want to fix on BSD: The assignment in #<span></span>1 would remove `const` from the right-hand side.

I see the following possible solutions:
- Add a configure probe for the exact type of the `tm_zone` field in `struct tm`, if present.
- Don't use individual variables to preserve/restore extra fields that `mini_mktime` doesn't know about; just use a full `struct tm`, whose fields are always compatible with itself.
