### ISSUE TITLE
Dereferencing an array constant

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#22100]
Given that line 3 works, would it not be reasonable to suppose that line 4 should work in the same way?

```
use v5.34;
$a = [1..2];
say STDERR @$a, " ", @{$a}, " ",  $a->@*, " ", @{[1..3]}, " ", [1..3]->@*; # 12 12 12 123 123                     - Line 3
say STDERR @[1..3];                                                        # Number found where operator expected - Line 4
```

**Comment by Grinnz** [comment]
The `@{}` syntax you demonstrated is required to dereference an expression, the only times the braces are not required are for simple variable names and scalars. This does not seem like a reasonable or useful addition to me, and you receive the error you do because it is currently parsed as the variable `@[`.

**Comment by mauke** [comment]
See also https://perldoc.perl.org/perlref#Simple-Scalar.

**Comment by Leont** [comment]
Philip, you keep posting these poorly thought-through ideas and we keep having to close them, this happened about two dozen times now. I hate saying this but maybe you should try doing something else because language design isn't your forte.
