### ISSUE TITLE
[doc] use VERSION - "use 5.12;" vs. "use strict;" and "use 5.35.0;" vs. "use warnings;"

### ISSUE THREAD

**Issue by pullrich** [Perl/perl5#22253]
**Where**

use VERSION

> If the specified Perl version is 5.12 or higher, strictures are enabled lexically as with use strict. Similarly, if the specified Perl version is 5.35.0 or higher, warnings are enabled. Later use of use VERSION will override all behavior of a previous use VERSION, possibly removing the strict, warnings, and feature added by it. use VERSION does not load the feature.pm, strict.pm, or warnings.pm files.

https://perldoc.perl.org/functions/use#use-VERSION

**Description**

I am confused. I thought specifying `use 5.12;` or higher would behave like `use strict;` ("... strictures are enabled lexically as with use strict."). But the last sentence in the paragraph warns me that strict.pm is then not loaded ... as it would be when using `use strict;`? (Same thing with `use warnings;` and version >= 5.35.0.)

So the correct thing to do, even at version 5.35.0 or later, would still be:
```
use v5.35.0;
use strict;
use warnings;
```
... to ensure that strictures and warnings are enabled *and* the *.pm's are loaded?

**Comment by Grinnz** [comment]
No, the stricture flags are the important bit, it avoids loading the .pm files because they are unnecessary overhead in that instance.

**Comment by mauke** [comment]
> I thought specifying `use 5.12;` or higher would behave like `use strict;` ("... strictures are enabled lexically as with use strict.").

Yes.

>  But the last sentence in the paragraph warns me that strict.pm is then not loaded ... as it would be when using `use strict;?`

Yes.

> So the correct thing to do, even at version 5.35.0 or later, would still be:
> 
>     use v5.35.0;
>     use strict;
>     use warnings;
> 
> ... to ensure that strictures and warnings are enabled and the *.pm's are loaded?

Depends on whether you need the \*.pm files to be loaded. Normally you don't, which is why `use v5.36` is enough (it enables warnings and strictures).

Additionally loading `strict.pm` is pointless: It has no other API or functionality other than to enable strictures.

You might need to load `warnings.pm` to configure how warnings are handled or to define your own custom warnings category, but the common case of just enabling all warnings (as with `use warnings;`) can also be done with a `use VERSION` declaration.

**Comment by Grinnz** [comment]
Clarified in #22254
