### ISSUE TITLE
Feature request: generate warnings in void context in assignment statements

### ISSUE THREAD

**Issue by EvanCarroll** [Perl/perl5#22261]
I wrote about this on StackOverflow when I observed it didn't generate a warning. This is the code,

```
$ perl -wE'sub foo {1}; sub bar {2}; sub baz {3}; my @foo = foo(), bar(), baz();
```

I found the underlying problem easily. But I think it may just be an oversight that it doesn't generate a warning. Seems pretty silly not to anyway.

https://stackoverflow.com/questions/78577874/why-are-functions-allowed-in-void-context-in-assignment-statements

**Comment by Grinnz** [comment]
The problem is this is not an "assignment statement", despite what it looks like to you knowing what your intent was; it is a statement with 3 expressions each executed in void context, one of which is an assignment. For instance, this is perfectly valid and extremely common, and the only difference is that the expressions are executed in list context: `foo(my $x = 42, $y, $z)`

**Comment by mauke** [comment]
What exactly are you requesting? Emit a warning whenever a function is called in void context?

**Comment by EvanCarroll** [comment]
@Grinnz that makes sense. Thanks.
