### ISSUE TITLE
[feature request] Build modules with `LINKTYPE=static` using bare CPAN or allow easy passing of build options

### ISSUE THREAD

**Issue by vadimkantorov** [Perl/perl5#22876]
I'm having to use manual download and module build snippets (figuring out versioned URLs and so forth - so all this is quite brittle) instead of just `cpan -T DBD::SQLite`. How could I pass in extra arguments for `Makefile.PL` using cpan? Specifically, I'm interested in `LINKTYPE=static` - to build modules' static libs.

Maybe some hack with some environment variables is possible?

```shell
PKG=DBD_SQLite
URL=https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.76.tar.gz
mkdir -p myext/$PKG
curl -L $URL | tar -xzf - --strip-components=1 --directory myext/$PKG
cd myext/$PKG
perl Makefile.PL LINKTYPE=static
make && make install
```

I found a similar discussion in https://www.perlmonks.org/?node_id=1204592, but 7-8 years have passed, so wondering if this has been tackled since in native cpan

**Comment by jkeenan** [comment]
> I'm having to use manual download and module build snippets (figuring out versioned URLs and so forth - so all this is quite brittle) instead of just `cpan -T DBD::SQLite`. How could I pass in extra arguments for `Makefile.PL` using cpan? Specifically, I'm interested in `LINKTYPE=static` - to build modules' static libs.
> 
> Maybe some hack with some environment variables is possible?
> 
>

...

> 
> I found a similar discussion in https://www.perlmonks.org/?node_id=1204592, but 7-8 years have passed, so wondering if this has been tackled since in native cpan

Since `CPAN` is distributed with the Perl 5 core distribution, you already have its source code at your disposal.  You can review its revision history at [Changes](https://metacpan.org/dist/CPAN/changes) or, for more detail, examine the [pull requests which have been applied](https://github.com/andk/cpanpm/pulls?q=is%3Apr+is%3Aclosed).  Given that `CPAN` is a dual-life module maintained upstream, to accomplish your objectives you will have to start with an issue in `CPAN`'s own [issue queue on GH](https://github.com/andk/cpanpm/issues).  That's where this feature request should be filed first.

**Comment by Grinnz** [comment]
EUMM takes PERL_MM_OPT and MB/MBT take PERL_MB_OPT. https://perldoc.perl.org/ExtUtils::MakeMaker#ENVIRONMENT https://metacpan.org/pod/Module::Build#Environment-variables https://metacpan.org/pod/Module::Build::Tiny#CONFIG-FILE-AND-ENVIRONMENT

I would suggest asking the [community](https://perldoc.perl.org/perlcommunity) questions like these.
